### ISSUE TITLE
2024 TPAC planning

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#1065]
Are there any topics we should discuss during TPAC in breakout sessions?

**Comment by justinfagnani** [comment]
A few things I'd like to discuss:

- Finishing scoped element registries MVP. I think the previous round of open questions was resolved, but there's a newer topic of how to use scopes when constructing detached trees that would be good to cover. I can help prep things to show the current status for this one.
 
- Theming. It's been a while since we tried to talk about theming from a high level. A lot of people are interested in "open styleable" for theming uses cases, not necessarily the backwards-compatibility with existing stylesheets use case, so I think it'd be good if we took some of the pressure off open-styleable to be all things by opening up the theming discussion again.

- Declarative CSS modules (deduping per-component CSS in SSR). Microsoft is very interested in this now and dedicating some time to work on it.

- DOM Parts, especially goals and constraints. Chrome's experimentation is ongoing, but so far a native implementation doesn't look like a slam-dunk performance win. Are there DX goals that justify the feature, or higher level features (like templating) that we should pursue?

I don't know if they all warrant their own session or should be grouped.

**Comment by rniwa** [comment]
@Westbrook : anything to add?

**Comment by Westbrook** [comment]
The couple of things I can think of based on our recent meetings:

- Are implementors outside of Chromium still aligned on https://github.com/WICG/webcomponents/blob/gh-pages/proposals/reference-target-explainer.md? It's been evolving a bit, and the initial implementation from the Microsoft team is coming close to done. It would be great to reconfirm that other implementors are onboard and what (if any) support the community can lend in furthering the **_absolutely most important_** issue we face an custom element authors.
- We're discussing a couple of CSS selector additions that it would be good to make sure implementors are aligned on:
  - The ability to match `:host:has(...)`, on top of the great work WebKit has done in support of `:host(:has(...))`: https://github.com/w3c/csswg-drafts/issues/10693
  - `:has-slotted(...)`: https://github.com/w3c/csswg-drafts/pull/10586
- And while thinking about CSS, getting insight into any blockers that implementors are seeing around bringing `... with { type: 'css' }` to the JS module system would be nice as well.

Baring any bad news, they should all fit as smaller conversations in a larger window, rather than needing their own individual blocks.

**Comment by rniwa** [comment]
Proposed scoped custom element registry as session: https://github.com/w3c/tpac2024-breakouts/issues/26

**Comment by rniwa** [comment]
Proposed open styleable shadow tree & theming as a session: https://github.com/w3c/tpac2024-breakouts/issues/27

**Comment by rniwa** [comment]
Proposed DOM parts as a session: https://github.com/w3c/tpac2024-breakouts/issues/28

**Comment by rniwa** [comment]
Proposed CSS modules as a session: https://github.com/w3c/tpac2024-breakouts/issues/29

**Comment by rniwa** [comment]
Proposed Web Components & ARIA as a session: https://github.com/w3c/tpac2024-breakouts/issues/30

**Comment by justinfagnani** [comment]
Re: DOM Parts. I wrote down one of the things I was thinking of as a motivation for DOM Parts outside of the pure performance vs a library of the low-level API, declarative templates in JS: https://github.com/WICG/webcomponents/issues/1069

**Comment by LeaVerou** [comment]
Proposed this breakout for a different theming issue (sharing design tokens between WCs and host page): https://github.com/w3c/tpac2024-breakouts/issues/92 / https://www.w3.org/events/meetings/a9540089-cb3a-413b-966a-8c1034b31b11/
Would love to have a co-chair if anyone is interested! Sadly, they scheduled it at the same time as two of other WC breakouts (despite them being listed as conflicts) 😖

**Comment by keithamus** [comment]
Happy to co-chair wherever I have no other conflicts.

**Comment by justinfagnani** [comment]
Speaking of chairs and co-chairs... @rniwa since you proposed these breakouts, you might be on the hook for them, but would you like other to take over chairing for them? I can certainly do a few of the ones I suggested.

**Comment by Westbrook** [comment]
@rniwa many thanks again for bringing all these sessions together. After another great TPAC, closing this scheduling issue.
