### ISSUE TITLE
Links on Introduction to Web Components don't actually take you anywhere

### ISSUE THREAD

**Issue by id4ho** [WICG/webcomponents#123]
On the "Introduction to Web Components" page I expected to be taken to the actual document when clicking on the following links:

![image](https://cloud.githubusercontent.com/assets/1232370/8268351/58be92d0-1737-11e5-99c2-6b355e2bf32a.png)

Instead, it stays on the same page with only a tiny abstract. Simply adding a 'publish' to the `Latest editor's draft` fixes that one (http://w3c.github.io/webcomponents/publish/explainer/), but I'm not sure how to fix the others.

Sorry if this is actually working as intended.

**Comment by hayatoito** [comment]
> Simply adding a 'publish' to the Latest editor's draft fixes that one (http://w3c.github.io/webcomponents/publish/explainer/),

I agree that "Latest editor's draft" is confusing name here because we don't continue to maintain "Introduction to Web Components".
However, I'm not sure whether it is worth or not to update the published NOTE [1] only for the reason.
[1] http://www.w3.org/TR/2014/NOTE-components-intro-20140724/

I'm afraid that we should make new version if we are updating a published one, If we follow W3C's procedure strictly. Can we leave the published note as is if this is not a significant issue?

**Comment by hayatoito** [comment]
Let me close this issue tentatively. Please feel free to reopen this. Thanks!
