### ISSUE TITLE
Scripts in HTML Imports should be scoped to the import (treat imports as script modules) (bugzilla: 27836)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#157]
Title: Scripts in HTML Imports should be scoped to the import (treat imports as script modules) (bugzilla: 27836)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27836

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27836#c0
_Ian 'Hixie' Hickson_ wrote on 2015-01-15 00:34:48 +0000.

Right now, two HTML imports will stomp on each other if they happen to declare the same globals. Each import should IMHO be in its own module and should export what it wants to export.

**Comment by TakayoshiKochi** [comment]
Once HTML Imports is redefined on top of ES6 modules, all `<script>` tags will be parsed as a module without `type=module` attribute?

**Comment by domenic** [comment]
I think that would be weird, personally. I hope we are able to come up with reasonable semantics for both classic and module scripts, inside an import.

**Comment by matthewp** [comment]
I don't think that's what this bug is about. I think the author is suggesting a way for an imported document to define exports, so that instead of calling `customElements.define` in a script within the import, you might instead export a custom element class that the consumer could then call `customElements.define` with.

Skipping past the hard parts of integrating the HTML import and ES module systems, let's say that was figured out, it would be nice if you could do something like:

``` js
import tabsDocument from './tabs.html';

const Tabs = tabsDocument.exports.default;

customElements.define('my-tabs', Tabs);
```

**Comment by TakayoshiKochi** [comment]
Let's continue this on https://github.com/w3c/webcomponents/issues/645.
