### ISSUE TITLE
[Imports]: Write introduction section (bugzilla: 21169)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#245]
Title: [Imports]: Write introduction section (bugzilla: 21169)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=21169

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=21169#c0
_Dimitri Glazkov_ wrote on 2013-03-02 00:05:39 +0000.

What problem packages solve? Why do we need them? What is the reasoning behind the chosen solution?

**Comment by TakayoshiKochi** [comment]
Let me close this issue as we do not spend time on HTML Imports moving forward.

This issue is obsolete.
For HTML Imports, https://www.html5rocks.com/en/tutorials/webcomponents/imports/ may be the best resource for introduction available today.

There are other discussions for packaging/modules
https://github.com/WICG/webpackage
https://github.com/w3c/webcomponents/issues/645
