### ISSUE TITLE
[Shadow] Section 2.4 - CSS inherit by default?

### ISSUE THREAD

**Issue by travisleithead** [WICG/webcomponents#314]
The spec says: 
["In resolving CSS inheritance, an element must inherit from the parent node in the composed tree, if applicable."](https://w3c.github.io/webcomponents/spec/shadow/index.html#composed-trees)

This implies that, in the general case, all CSS properties that inherit by default will automatically bridge shadow dom boundaries, and that the use of the CSS value `inherit` will potentially pull styling from across shadow dom boundaries as well.

Is this the behavior that we want? Clearly, for our styling story, we _do_ want CSS custom properties to inherit through shadow dom boundaries, but this should be the exception, not the default.

**Comment by hayatoito** [comment]
That's intentional behavior for years. In short:
1. Style inherits _by default_
2. CSS Selector matching doesn't span shadow boundaries _by default_, except for special selectors, such as :content, :host, ::shadow, >>> (aka /deep/), some of which are already dead.

CSS custom properties are mainly used for overcoming the limitation of 2, instead of 1, I think

FYI, For component authors who don't want a style inheritance, Shadow DOM had `resetStyleInheritance` attribute in the past. But we removed this attribute in favor of CSS property `all`. `all: initial` should have the same effect.

**Comment by rniwa** [comment]
I'm not certain inheriting by default makes sense for _closed_ shadow tree.  We might want to make it inherit by default for _open_ shadow trees and not inherit by default for _closed_ shadow trees.

**Comment by hayatoito** [comment]
How style inheritance should behave for closed shadow trees is not well thought out.
We should decide it.

**Comment by rniwa** [comment]
The consensus from the meeting on Friday was to make shadow DOM _not inherit_ style by default.

**Comment by dglazkov** [comment]
I believe it was a bit more nuanced than that:
- We all agreed that open and closed mode should not differ in how they inherit styles
- There was concern over erasing UA stylesheet and a discussion abut the "revert" value.

I think we should experiment with existing body of work (Polymer has a bunch of elements) and see how this pans out. For example, we're leaning on CSS custom properties for styling in Shadow DOM. Aren't those heavily dependent on inheritance?

**Comment by rniwa** [comment]
Just to clarity, we don't necessarily think custom properties is the best way to style components that use shadow tree.  In particular, we're a lot more interested in adding back mechanism to define custom pseudo elements.

**Comment by dglazkov** [comment]
Please sanity-check this with Front-end folks, like @sorvell and @JanMiksovsky. My understanding is that custom pseudos are a useful addition, but they aren't a replacement for custom properties.

**Comment by rniwa** [comment]
Neither are custom properties a replacement for custom pseudos.  It's a matter of prioritization and use cases we care about.  To be clear, I'm not saying custom properties are bad idea or that we don't want to support it. It's that we care more about pseudo elements than custom properties in terms of prioritization.

**Comment by dglazkov** [comment]
Got it. That helps.

**Comment by travisleithead** [comment]
@rniwa do you have any thoughts on @tabatkins custom property sets? http://tabatkins.github.io/specs/css-apply-rule/

**Comment by TakayoshiKochi** [comment]
It seems that the discussion about custom properties/custom pseudos/custom property sets can be a
different issue than this thread was about originally, that is, whether styles are inherited at
shadow boundary or not.  Is it #300?

Back to the original problem, we still can be either way.

Blink adopts 'inherit style by default' for both open/closed (and UA) shadows. As esprehn explained,
the behavior is consistent with platform (e.g. <input> is composed of UA shadows, say, setting
input { font-size: xx; } can affect the font size inside <input>'s internal editing area etc.).

When we adopt "not inherit by default" (for both open/closed shadows, as @dglazkov say),
how we allow inheriting of specific properties on a shadow boundary?
(e.g. ShadowRoot.allowStyleInheritance = "font-size" or in CSS, ":root { font-size: inherit }
any ideas?)

Also, how is a distributed element styled? e.g.

``` html
<div>
   :shadow-root
       <slot>
           ...slotted <span> inserted here
       </slot>
   <span>How am I styled?</span>
</div>
```

There is also a boundary between <slot> and slotted <span> in the composed tree.

**Comment by rniwa** [comment]
> Blink adopts 'inherit style by default' for both open/closed (and UA) shadows. As esprehn explained,
> the behavior is consistent with platform (e.g. is composed of UA shadows, say, setting
> input { font-size: xx; } can affect the font size inside 's internal editing area etc.).

On the other hand, `<b><button>hello</button></b>` does not bold the text inside the button so the platform itself is quite inconsistent at the moment.

> When we adopt "not inherit by default" (for both open/closed shadows, as @dglazkov say),
> how we allow inheriting of specific properties on a shadow boundary?

`:host {font-size: inherit}` would do since ShadowRoot doesn't generate a CSS box (like an element with `display: contents`).

> Also, how is a distributed element styled?

How a slotted element styled and whether style should inherit from slot elements that got assigned of those elements is a separate question.  Let's not conflate that discussion into here.

**Comment by TakayoshiKochi** [comment]
> On the other hand, `<b><button>hello</button></b>` does not bold the text inside the button so the platform itself is quite inconsistent at the moment.

Indeed it is not get bolden.  Looking at this in Chrome's inspector, the `<b>`'s style is inherited,
but is reset by UA stylesheet (and Chome's `<button>` doesn't use UA shadow btw).

The same goes for `<b><input value="foo"></b>`, in this case the content of `<input>` doesn't
get bolden, but `<input style="font-weight: bold" value="foo">` works.
Likewise, `<button style="font-weight: bold">hello</button>` also works.

> `:host {font-size: inherit}` would do since ShadowRoot doesn't generate a CSS box (like an element with `display: contents`).

Isn't `:host {font-size: inherit}` from shadow tree same as `div#host {font-size: inherit}` from
the document?  The shadow host inherits `font-size` style from its parent, but does
it mean it will also be inherited by its shadow?
Or did you mean `:root`?  Even though it does not create a box, it should be able to specify
some property to be inherited.

> How a slotted element styled and whether style should inherit from slot elements that got assigned of those elements is a separate question. Let's not conflate that discussion into here.

Do we have already a filed issue for this?

**Comment by hayatoito** [comment]
I'm back from the vacation. Let me catch up the discussion.

I don't see the clear definition of "not inherit style by default".
Could someone clarify the behavior at first?

If it is difficult to explain formally, I appreciate the explanation using the example tree of trees in the spec [1]:
- Which nodes inherit a style from the parent node in the composed tree, and which nodes do not?

Please leave a slot element to the composed tree if that's required to explain the behavior.

Additional question:
- For a node which doesn't inherit, where `{all: inherit}` should be used to _flip_ the behavior? Do we need an additional primitive other than {all: inherit} to _flip_ the behavior?

[1] http://w3c.github.io/webcomponents/spec/shadow/#composition-example

**Comment by rniwa** [comment]
See [2.3 composed trees](https://w3c.github.io/webcomponents/spec/shadow/index.html#composed-trees) where it says:

> In resolving CSS inheritance, an element **must** inherit from the parent node in the composed tree, if applicable.

The question is whether that behavior is desirable or not.  During F2F/telecon we had a week ago, there was a lot of confusion about inheritance and cascading.  I think we might need another F2F/telecon to clarify the situation.  This is all too confusing.

**Comment by hayatoito** [comment]
Thanks.

IMO, "CSS inherit by default" makes sense. I've never heard a complaint about this default behavior from front-end folks for years. That would be a desired behavior in most cases in the real world, I guess.
I am not sure whether this is a desired behavior or not for a closed mode. I don't have any data.

If this is an undesirable behavior, we should make an alternative proposal where the behavior is clearly defined so that we can discuss the pros and cons.

**Comment by rniwa** [comment]
On what basis does it make sense?  I can hypothesize, for example, that the reason people have not complained about "inherit by default" behavior might be that they're used to working around it elsewhere by resetting styles.  We should spec the **desired** behavior as the default instead of an **acceptable** behavior.

One point I made during the meeting is that you can emulate inheritance by default behavior by `all: inherit` but you can't quite do `all: initial` to emulate the other behavior since that would also reset UA stylesheets.

**Comment by hayatoito** [comment]
Yeah, that's my opinion and guess. We need data in the real world. We need help from front-end folks to know the desired behavior, as @dglazkov requested help in https://github.com/w3c/webcomponents/issues/314#issuecomment-142354163 .

The points are:
- There is an opinion that the current behavior might be questionable.
- However, I don't see a clearly-defined alternative idea in the discussion so far. I'd like to see a clear proposal, instead of just a question.

An alternative idea should define the following two algorithms, or equivalent:

1.
Input: NODE, a node
Output: (nullable) PARENT, from where NODE inherits a style if it should inherit.

2.
Input: NODE, a node
Output: boolean flag, whether NODE inherits a style from PARENT by default or not

The current behavior is:
1. The parent node of NODE in the composed tree
2. true, always

**Comment by dglazkov** [comment]
To add a bit more, I would love to understand the concern with resetting UA stylesheets. Off the top of my head, I can't think of a situation where that would be a problem.

**Comment by tabatkins** [comment]
I really wish I hadn't been sick, and forced to skip that f2f, because I could have cleared up a lot of confusion. :/

We should be inheriting by default.  It's what _all_ shadow-root-ish things in the platform do today, it's what all components have done since we initially implemented them.  It's required for variables to work, at the bare minimum.

If you want to shut down inheritance entirely, you have the `all: revert` declaration (which forces the element to ignore all author-level styling, styling it as if only the UA and user stylesheets existed).  The opposite way, forcing inheritance, is done by `all: unset`, which causes the element to either take its inherited or initial value, as appropriate.

For further styling, beyond what's reasonable to do with variables, we have [the @apply rule](https://tabatkins.github.io/specs/css-apply-rule/), which the WG approved work on.  It needs some clarifications (hammered out in the meeting) to avoid circularity, and then it needs to be moved into the WG repository, but it's otherwise done.  It allows passing an entire ruleset via the variables mechanism, so the component author can allow arbitrary styling of a shadow-tree element without exposing a ton of variables.

There's one hole remaining in this functionality - the ability to style a shadow-tree element based on states, like :hover or :active.  Handling this with `@apply` as written gives the same problems as before - the component author has to define a ton of variables for all the combinations of states that they want to expose.  This then calls for [CSS Rule Nesting](https://tabatkins.github.io/specs/css-nesting/), which I recently revised (and which is _insanely popular_ among webdevs).

Between Variables, and the combination of `@apply` and Nesting, all styling needs are taken care of, as far as I can tell.  There's no need to invent a new pseudo-element functionality.

**Comment by TakayoshiKochi** [comment]
Thanks Tab - `all: unset` is already in CSS Cascading and Inheritance Level 3, but
as fantasai said in the last conf, `all: revert` isn't specced yet, right?

What is the odds that `all: revert` can be in the spec in near future?

**Comment by tabatkins** [comment]
It's already specced https://drafts.csswg.org/css-cascade/#default

**Comment by TakayoshiKochi** [comment]
@tabatkins Aha, thanks!

**Comment by hayatoito** [comment]
I think we can close this issue tentatively.

I'm feeling that it might be a bit early to close this issue, so please feel free to re-open this issue if someone has a concrete well-defined proposal which is different from the current behavior.
