### ISSUE TITLE
[Shadow] Need equivalent of ownerDocument for Elements in a shadow tree to get to their ShadowRoot

### ISSUE THREAD

**Issue by travisleithead** [WICG/webcomponents#315]
For an element participating in a shadow tree (and only interested in performing DOM searches scoped to its own shadow tree, it will often be necessary to use it's "owner shadow root" object to perform these searches. For example, shadowRoot.getElementById, or shadowRoot.querySelector. However, there is no convenient link from an element in a shadow tree to grab its shadow root container.

I propose extending Node with a new property `ownerShadowRoot` (or possibly `parentShadowRoot`) in order to provide this linkage.

This property also doubles as a convenient check for "am I in a shadow tree", as the `ownerShadowRoot` property would be null for any node in the document tree.

**Comment by rniwa** [comment]
Alternatively, would it make sense to add `rootNode` attribute which returns the root node in any node tree?  This would work for document fragment, detached nodes, etc...

**Comment by domenic** [comment]
Bikeshed: `closestShadowRoot` to match [`Element.prototype.closest`](https://dom.spec.whatwg.org/#dom-element-closest).

@rniwa hmm I do like that a lot. The document fragment and detached node use cases are good ones. Although naming is a bit hard. I'd have a hard time justifying rootNode stopping at shadow roots instead of keeping going past them. (I guess because I think of them as "_shadow_ roots", not "shadow _roots_", if that makes any sense.) Also, do you think it would require a tree walk? If so maybe it would be better as a method instead of a getter.

**Comment by rniwa** [comment]
@domenic : In WebKit and Blink, it would require tree walking only in the case of a detached subtree that doesn't have a ShadowRoot.  Nodes that are in a document and/or in a shadow tree can return its root node in O(1).  I'd imagine some engines could always compute it in O(1).

**Comment by hayatoito** [comment]
I remember the similar request was filed in the past in the bugzilla. Let me find that.

**Comment by hayatoito** [comment]
Let me merge this with https://github.com/w3c/webcomponents/issues/80
