### ISSUE TITLE
Shadow DOM Cascade Order

### ISSUE THREAD

**Issue by kojiishi** [WICG/webcomponents#316]
The [Shadow DOM Cascade Order proposal](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Shadow-DOM-Cascade-Order.md) asks for clarifications on cascading order of style attributes in its [clarification](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Shadow-DOM-Cascade-Order.md#clarification) section. I think it's worth a separate topic, and this issue is for it.

The proposal suggests:

> declarations from style attributes should belong to the same tree in terms of cascading as the element on which it is set.

Let's call this **Option 1**, and I'd like to seek for what are other sensible options.

Historically, a style attribute is defined to have the highest specificity in CSS 2.1 and [Cascading in CSS Style Attributes](https://drafts.csswg.org/css-style-attr/#interpret). When [**Scope**](http://dev.w3.org/csswg/css-cascade-3/#cascade-scope) is added between **Origin** and **Specificity**, a style attribute was adjusted to have the highest precedence in the **Scope** (see Notes in the spec.)

If we were to do similarly for the [**Shadow Tree**](http://dev.w3.org/csswg/css-scoping-1/#cascading) cascade criteria, following two options look reasonable to consider:

| Precedence | Option 1 | Option 2 | Option 3 |
| --- | --- | --- | --- |
| Higher |  | Important attributes | Important attributes |
|  | Important Inner | Important inner | Important inner |
|  | Important attributes and elements | Important elements | Important elements |
|  | Important outer | Important outer | Important outer |
|  |  | Normal attributes | Normal outer |
|  | Normal outer | Normal outer | Normal attributes |
|  | Normal attributes and elements | Normal elements | Normal elements |
| Lower | Normal inner | Normal inner | Normal inner |

Thoughts?

**Comment by ghost** [comment]
Note that without piercing combinators, the element and its style attribute are always in the outermost shadow tree from which rules are applied.

My reasoning behind suggesting the style attribute declarations should be grouped with the rules from the stylesheets in the same (shadow) tree as the element, is that for:

```
<style>
my-item { color:green; background:lime !important }
</style>

<my-list>
  <:shadow>
    <style>::content my-item { color:red; background-color: orange !important }</style>
    <content/>
  </:shadow>
  <my-item style="color:green; background:lime !important"></my-item>
</my-component>
```

whether the style is set through a stylesheet rule or a style attribute in the outer scope, should not affect the cascading order relative to the with the ::content rule in inner scope. With my cascading proposal, you would use !important to override with the ::content rule.

What made me a bit uncertain was the special casing for style attributes for <style scoped> in the css-cascade spec.

**Comment by rniwa** [comment]
After discussing briefly with my colleagues, we like option 2 for its consistency with the existing model.

**Comment by kojiishi** [comment]
> What made me a bit uncertain was the special casing for style attributes for in the css-cascade spec.

After this issue was brought up, I gave some thoughts on it, and my understanding of CSS 2.1 is that:
1. Semantically it looks more like a scoped to the element, and making it stronger is intuitive.
2. It allows JS to override rules by setting style attributes to `display:none` (or vice versa) to toggle.

For those reasons, and since it's already at the top of the specificity, it makes sense for Scoped to bring it up further, to the highest in Scoped criteria.

Now for the Shadow DOM criteria, as @rune-opera mentioned, it only affects `::content` and such tree-boundary-crossing-rules, so not doing the same originally made sense to me, and I still like its simplicity.

On the other hand, when component user sets, say, `::content my-item { display:flex }`, component authors must use `!important` to style attributes if we go with option 1. It may be rare in the current design, but needing "!important" to style attributes does not look very intuitive, and may break many libraries such as jQuery .hide(). From that view point, I agree with @rniwa, option 2 gives more familiar experiences to web developers.

**Comment by tabatkins** [comment]
Okay, bringing in a full example, as there are now four different ways styles can interact on a single element:

``` html
<style id=page>menuitem { color: red; }</style>
<menu>
  <::shadow>
    <style id=content>::content menuitem { color: green; }</style>
    <content select="menuitem">
  </::shadow>
  <menuitem style="color: yellow;">
    <::shadow>
      <style id=host>:host { color: blue; }</style>
      ...
    </::shadow>
  </menuitem>
</menu>
```

We have the following principles that should be honored:
1. Style attr is "scoped" to the element. Scoped rules know better what styling should happen than "generic" outer page rules, so they should usually win. Since they're intermixed with generic rules, we need to give them an auto-win, reversible with !important. Handled by the **Scoping** cascade step.
2. Shadow styles are the opposite - "generic" rules from outside don't apply at all, so the shadow rules "win" by default. Since outer page rules intruding are special-case and intentional, we can let them auto-win against shadow rules. !important reverses this, allowing the shadow to set invariants. Handled by the **Shadow Tree** cascade step, which occurs before **Scoping**.
3. :host vs outer page is a little different. "Generic" rules from the outer doc can hit the host element, so the reasoning doesn't hold as strongly, but simplicity in handling shadow stuff dictates it should agree with normal shadow rules (plus the default/invariant dichotomy seems useful here, too).
4. ::content is the same - they intermix with "generic" rules, but simplicity in shadows, plus usefulness of the default/invariant dichotomy, suggests they agree with the normal shadow rules.

So we have:
- inline > page
- page > content
- page > host
- inline > content && inline > host (both by transitivity, and by direct application - it's from the outer page, and so wins against shadow rules)
- content <?> host

It's just ::content vs :host that we have to deal with. I don't have a strong opinion on which one should win, but it _feels_ like ::content rules are similar to outer-page rules, relative to :host rules, and so they should act the same and win.

That would give us an ordering of `inline > page > content > host`.

If !important is used, on any single element it auto-wins due to the **Origin** cascade step. If everyone's important, then:
- host beats content, per the "shadow beats outer page when !important" rule in the **Shadow Tree** cascade step (assuming we decide that ::content is "outer page" relative to :host)
- host beats page and inline, same reason
- content beats page and inline, same reason
- inline beats page, per the **Specificity** cascade step.

So we have almost an opposite ordering: `host > content > inline > page`.

Does this all sound good to everyone?  If so, I'll figure out how to wordsmith the "::content is considered to be in an ancestor tree relative to :host" thing.

**Comment by ghost** [comment]
Yes, this is in line with what I proposed in the [Shadow DOM Cascade Order proposal](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Shadow-DOM-Cascade-Order.md), but it was more general in the sense that the shadow tree cascading was expressed in terms of shadow tree order and was selector-agnostic. That was also necessary since in shadow dom v0, ::content rules from different shadow trees may apply to the same element. Did we land on a more restrictive "scope" or even a name for "::slotted" yet?

**Comment by tabatkins** [comment]
Yeah, some internal discussion realized that I'd missed multiple levels of ::content.  We're leaning towards just letting you target the directly-slotted elements, in which case that disappears.

That sound cool?

**Comment by rniwa** [comment]
Here's the above example in the new syntax:

``` html
<style id=page>menuitem { color: red; }</style>
<menu>
  <!--shadow-root-start-->
    <style id=content>::slotted menuitem { color: green; }</style>
    <slot></slot>
  <!--shadow-root-end-->
  <menuitem style="color: yellow;">
    <!--shadow-root-start-->
      <style id=host>:host { color: blue; }</style>
      ...
    <!--shadow-root-end-->
  </menuitem>
</menu>
```

And you're suggesting inline > #page > #content > #host for non-`!important` case and #host > #content > #inline > #page?  I'd say that the inversion between content and page is a little weird.

**Comment by tabatkins** [comment]
What do you mean by "between content and page"? Their ordering is reversed as one would expect. It's inline and page that don't reverse, because that's how styles work today.

**Comment by rniwa** [comment]
Oops, I meant to say the reversion between #host and #content.  I guess the reversion occurs at shadow boundary is what it is.  #host and #content rules are coming from different shadow trees so it kind of makes sense that their ordering changes.

**Comment by tabatkins** [comment]
Yeah, it's the same principle behind #page and #host inverting.  As far as #host is concerned, #content is styles from "outside" poking in, so the default/invariant dichotomy applies and #content wins by default, but loses when !important.

**Comment by hayatoito** [comment]
I summarized the current situation since we have a meeting on W3C TPAC 2015 tomorrow.

See https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Shadow-DOM-Cascade-Order-in-v1.md.

Because everyone I've met has some kind of confusion on this issue, we need to have a good summary to have a good discussion tomorrow, definitely.

I appreciate if you could take a look at the summary of the proposals in the document before the meeting.
I'd like to have a tentative resolution in the meeting tomorrow.

I wrote this document in an hour, so please forgive me if I miss something important.
I appreciate pull-requests or comments anytime before the meeting.

**Comment by hayatoito** [comment]
As far as my understanding is correct, everyone looks okay with _Proposal 1_ mentioned in https://lists.w3.org/Archives/Public/public-webapps/2015OctDec/0149.html

Proposal 1 is:

> [E !important] > [D !important] > [C !important] > [style-attribute !important] > [B !important] > [A !important] > [A] > [style-attribute] > [B] > [C] > [D] > [E]
- _Proposal 1_ doesn't conflict with @rune-opera 's proposal.
- Apple (@rniwa) likes Option2, which doesn't conflict _Proposal 1_. In W3C TPAC, we also had a casual chat that "Outer wins Inner" would make sense.
- @kojiishi suggested Option1, but the reason for that is for the compatibility issue in Blink. We are okay with _Proposal 1_ if we can resolve the backward compatibility issue in Blink.

Thus, to have _Proposal 1_ in the spec, the only remaining concern is the backward compatibility issue in Blink.
@TakayoshiKochi is investigation on that. We can update this issue if we can figure out something about that.

**Comment by TakayoshiKochi** [comment]
Following up the previous @hayatoito 's comment:

_Proposal1_ and _Proposal2_ are at the bottom of @hayatoito 's [proposal doc](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Shadow-DOM-Cascade-Order-in-v1.md), which says essentially 2 things if I sum up:
- Rules coming from other shadow trees are compared in tree-of-trees order (as proposed by @rune-opera 's original proposal).
- Regarding how style attribute is compared against other style rules defined in stylesheet (which is the original topic of this thread), Proposal1 follows Option1 in this thread , and Proposal2 follows Option2.

Regarding the former, "Outer wins Inner" is a rule of thumb and inaccurate.  Comparison in terms of tree-of-trees order is more comprehensive and precise definition, as @rune-opera already mentioned.  I think all of us in this thread agree on this.  Both Hayato's _Proposal1_ and _Proposal2_ follow this comparison order.

For the latter, which is still unresolved.
On the previous @hayatoito 's comment's second bullet, "... likes Option2, which doesn't conflict _Proposal 1_" but actually it **conflicts**.  If nothing changed, Apple still wants _Proposal2_ behavior?

To be consistent with how style attribute is handled in scoped style, Option 1 (or Hayato's _Proposal 1_) looks a reasonable choice to me.

At this moment I don't think the feasibility to keep the backward compatibility for Blink implementation is irrelevant to which option we take.

**Comment by dglazkov** [comment]
Am I reading this wrong or are the `A` styles actually stomp on the inline styles in _Proposal 1_?

**Comment by TakayoshiKochi** [comment]
IIUC in _Proposal 1_ a style rule in `A` wins against inline style of an element in `B` tree.
This situation can't happen (as Hayato wrote in the document) without `/deep/` and `::shadow`,
but considering custom pseudo elements, `A` could win against inline style.

Quoting Hayato's doc:

> As I said, [A] never matches an element in B in the current spec. However, if we support custom pseudo elements, Issue #300 , we should consider it. That's the reason I've added [A] there.

**Comment by hayatoito** [comment]
Yeah, we can ignore `[A (parent tree)]` vs `[inline style attribute (in child tree, B)]` for a while because that does not happen in a world without `/deep/` nor `::shadow`.

**Comment by dglazkov** [comment]
Makes sense. So, it's basically a theoretical situation that will never happen in practice?

**Comment by hayatoito** [comment]
Yeah, I can not find any case where this situation happens.
If someone find the case, please tell us.

**Comment by TakayoshiKochi** [comment]
Any objections?

I'd like to wrap this up, upstreaming the proposal to CSS Scoping level1 spec.
@tabatkins what's the recommended way?

**Comment by tabatkins** [comment]
Best would probably be to send an email to www-style with the proposal (so everyone can see it), and then I'll make the edits.

**Comment by TakayoshiKochi** [comment]
@tabatkins thanks, I'll do.

**Comment by TakayoshiKochi** [comment]
Posted to www-style.
https://lists.w3.org/Archives/Public/www-style/2016Mar/0056.html

**Comment by hayatoito** [comment]
@TakayoshiKochi 
Is there any update on this issue? I think all we have to do is to upstream the current consensus to CSS Scoping.

**Comment by TakayoshiKochi** [comment]
I'm contacting @tabatkins to get the spec updated.

**Comment by TakayoshiKochi** [comment]
The spec change is upstreamed in
https://drafts.csswg.org/css-scoping-1/#shadow-cascading

**Comment by rniwa** [comment]
Closing the issue since the proposal has been merged into a CSS WG's spec.
