### ISSUE TITLE
Spec examples need to be updated to use the new syntax

### ISSUE THREAD

**Issue by dglazkov** [WICG/webcomponents#318]
Still uses the `<content>` element.

**Comment by ebidel** [comment]
Specifically the examples still use insertion points. very confusing!

**Comment by hayatoito** [comment]
Yeah, let me do it. However, the problem is:

As far as I remember, I tried to update the example in a few weeks ago, but I couldn't do it _mechanically_ because the original _scenario_ would become unnatural one because it requires invasive _slot_ attributes being there, in code example 2, before Bob decides to use shadow DOM. 

It says:

> Bob decides to use shadow DOM. Doing so will allow Bob to keep the document markup uncluttered, 

Unfortunately, if there are slots attributes in code example2, it looks very unnatural because no one has decided to use Shadow DOM at that time. Slots attributes are very invasive, compared to class attributes.

If Bob has to modify the document markup when he decides to use Shadow DOM, the scenario would lose the point.

**Comment by hayatoito** [comment]
Anyway, I've updated the example so it uses slots.
