### ISSUE TITLE
deepPath should return an empty array if it's no longer being dispatched

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#373]
`deepPath()` should return an empty array if it's no longer being dispatched instead of returning the last node's event path since any code can keep a reference to `Event` object and later get access to nodes besides [unclosed nodes](http://w3c.github.io/webcomponents/spec/shadow/#dfn-unclosed-node) (i.e. closed nodes that they shouldn't have access to).

In addition, retaining the entire event path will force UAs to keep all nodes in the event path alive as long as `Event` object is alive, which is expensive.

Also, the definition of step 2.4: "Let PATH contain only a node which is an unclosed node of CURRENT-TARGET" seems rather vague.  I think it's better to say "remove any node that is not an unclosed node from PATH" instead so that the ordering of nodes inside the path is preserved (without having to say so explicitly).

The definition should also prefer to the concept of [dispatch](https://dom.spec.whatwg.org/#dispatching-events) in DOM4 as well as the [dispatch flag](https://dom.spec.whatwg.org/#dispatch-flag).

**Comment by hayatoito** [comment]
I remember that event.path returned an empty array in the past, but I changed the behavior after I received the feedback. The context is: https://code.google.com/p/chromium/issues/detail?id=402749

I'm fine that deepPath() would return an empty array after the event dispatch is done.
I think the original issue is no longer applied because deepPath() is now a method.

However, I would like to wait for another feedback from web developers for this change. We should make a decision in terms of the usability of the API.

> since any code can keep a reference to Event object and later get access to nodes besides unclosed nodes (i.e. closed nodes that they shouldn't have access to).

This should not happen. After the dispatching, event.deepPath() returns unclosed nodes from the view of the document tree. Thus, an encapsulation does not break.

**Comment by rniwa** [comment]
> This should not happen. After the dispatching, event.deepPath() returns unclosed nodes from the view of the document tree. Thus, an encapsulation does not break.

That's not necessary true when the event path is trimmed, is it?  If we're making `deepPath()` always use the untrimmed full path instead of the trimmed path, then we should explicitly state that.

**Comment by hayatoito** [comment]
I see. However, even in a such a case, an encapsulation does not break unless developers leak an event object _intentionally_, such as assigning it to a global variable.

**Comment by hayatoito** [comment]
@ebidel
Is it okay to make event.deepPath() return an empty array after an event dispatching is done?

I remember the discussion here:
https://code.google.com/p/chromium/issues/detail?id=401947

The situation has changed since then. Event.deepPath() is now a method.

**Comment by ebidel** [comment]
Yea, this now requires a call from the developer...so  I think it's different now. Before, it was confusing that inspecting in the console have you unexpected results.

**Comment by hayatoito** [comment]
I got it. Thanks.
