### ISSUE TITLE
"component tree" is just "node tree"

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#384]
It seems that the concept of [a component tree](https://w3c.github.io/webcomponents/spec/shadow/#dfn-component-tree) is redundant with [node tree](https://dom.spec.whatwg.org/#concept-node-tree).

Also I don't like the term [A primary component tree](https://w3c.github.io/webcomponents/spec/shadow/#dfn-primary-component-tree).  "component" seems like an arbitrary prefix that doesn't add any value;  It makes me think of a Web component, and that's a bad thing.  I think "primary tree" would be a better name.

Also, why is `DocumentFragment` left out in this concept?  All shadow root should be document fragments, right?

**Comment by hayatoito** [comment]
See the followings for details:
- https://github.com/w3c/webcomponents/issues/382#issuecomment-184700676
- https://github.com/w3c/webcomponents/issues/382#issuecomment-184732751

I would like to defer the decision because it depends on https://github.com/w3c/webcomponents/issues/382#issuecomment-184700676

If we decide not to support the distribution for a composed tree whose root tree is not a document tree, we can define a component tree as either a document tree or a shadow tree, and can remove the other terminologies - _fragment tree_ and _primary component tree_. We do not have to update other parts of the spec. That's one of the reasons I use "component tree" as an _alias_, as of now.

> Also, why is DocumentFragment left out in this concept? All shadow root should be document fragments, right?

A DocumentFragment which is not a shadow root:
- is a node tree
- is a fragment tree
- is a component tree
- is not a primary component tree

**Comment by annevk** [comment]
This was fixed through https://github.com/w3c/webcomponents/commit/0113437598395832d5f308377fde6013495ad43b.
