### ISSUE TITLE
Define the behavior for sync element creation when a custom element constructor does various bad things

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#412]
What should the HTML parser do when a custom element constructor it involved ends up inserting the element before returning to the parser?

More specifically, we need to consider the case where the returned element is a new element inserted into the document at the "right" location, a random other location, and into another document.  Should we re-adopt the element and insert into the document we're parsing?  Or should we leave the element alone?

We need to define this behavior somehow.

**Comment by annevk** [comment]
More generally, the problem here is the constructor returning an element that already has a parent?

**Comment by rniwa** [comment]
Yes.

**Comment by domenic** [comment]
I think this is only relevant in the non-upgrade case, so for createElement and the parser. Does that sound right?

I think it would be reasonable to throw (=> htmlunknownelement in parser case) if the constructor returns an element with non-null parent.

**Comment by domenic** [comment]
I guess in the upgrade case we could also "report an exception", or alternately just have developer tools provide a warning that the return value will be ignored.

**Comment by rniwa** [comment]
I don't think we need to do anything in the upgrade case because if the element had been re-parented to somewhere else, there is no way for us to fix it.  `IsSameValue` check is probably sufficient in that case.

For HTML parser, though, we need to be even more careful.  e.g. what happens if the constructor returned an element with non-zero attributes?  Or an element with a wrong prefix in its qualified name?  Or it returned an element with a child?

**Comment by annevk** [comment]
@rniwa what problems do you envision with simply inserting such elements?

**Comment by rniwa** [comment]
@annevk : I don't really but I think the spec should call out, at least in non-normative note, as to what happens when they do.

**Comment by domenic** [comment]
So, what is the conclusion here, in terms of modifications to the current spec? That is, given the two synchronous-construction cases:
- createElement(NS)
- the parser

and the following possible things that could go wrong:
- wrong prefix
- wrong localName
- wrong namespace
- has attributes
- has a parent
- has children

What additional checks do we insert, in which cases?

Or do we just insert a non-normative note (in the "create an element" algorithm's "If synchronous custom elements flag is set" section) saying that the returned element may have some of these things having gone wrong?

**Comment by rniwa** [comment]
- wrong owner document
- owner interface (i.e. instantiate X, constructor returns Y)

**Comment by domenic** [comment]
My initial thought is that we should check all of these, because they seem like good things to enforce. But, would that be a performance worry?

Maybe it's better to just tell people to not do dumb things, and if they do, then their documents get weird? I don't think we're protecting any important invariants here, are we?

**Comment by rniwa** [comment]
I don't think checking the equality of qualified names and/or presence of attributes/children is that expensive.  Checking `instsanceof` would be though so perhaps we should omit that and just check the brand (e.g. make sure new MyElement doesn't return, say, HTMLIframeElement).

**Comment by domenic** [comment]
In https://github.com/w3c/webcomponents/commit/70ec265b9ca766836d22bd76f6062b7d66e67950 I implemented all of the checks discussed here, with the following slight tweaks:
- Instead of checking instanceof in some way, I just do a shallow [[Prototype]] check.
- Instead of checking prefix, I have the element construction algorithm actually set the supplied prefix automatically for you. This allows `document.createElement(HTML_NS, "foo:x-tag")` to work and give an element with prefix `foo` and local name `x-tag`, just like `document.createElement(HTML_NS, "foo:p")` works.
