### ISSUE TITLE
Rename the first argument of defineElement from type to localName

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#416]
[`defineElement`](https://w3c.github.io/webcomponents/spec/custom/#dom-document-defineelement)'s first argument should be renamed to `localName`.

`type` is a very generic term and could refer to anything whereas `localName` in the context of DOM API is understood to refer to a [specific meaning](https://dom.spec.whatwg.org/#concept-element-local-name) and also matches the [definition of `createElement`](https://dom.spec.whatwg.org/#dom-document-createelement).

**Comment by domenic** [comment]
Although I agree type is not a great word, I think it's important to distinguish from localName, because of the type extensions/ { is } version.

Assuming #408, then if you do

``` js
document.defineElement("super-a", XFoo, { extends: "a" });

document.createElement("a", { is: "super-a" });
```

then the resulting local name of such elements will be `"a"`, not `"super-a"`.

I also think it's important to have a term for what is currently "valid custom element type".

**Comment by annevk** [comment]
Maybe just use "name"? (It does somewhat make sense not to use localName here since it'll have different restrictions placed on it for now per the ASCII issue.) And make "custom element type" not refer to the name, but to a particular brand of element.

**Comment by rniwa** [comment]
Oh I see. Yeah, `name` would be better.
