### ISSUE TITLE
defineElement should not cache lifecycle callbacks and prototype of a custom element class

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#417]
During Jan F2F, Google made an argument that we need to cache the lifecycle callbacks to avoid enqueueing unnecessary items (e.g. when `attributeChangedCallback` is missing) but we (Apple) no longer think this is an acceptable behavior.

This behavior precludes authors from overriding method on a particular instance of a custom element. In order to change even a single instance's behavior, you would have to define a new custom element or make the element call its own delegate method which is unnecessary boilerplate.

In addition, we think modern JS engines are fully capable of detecting changes in JS object's structure for optimization purposes and if Google and other implementors wanted to avoid enqueuing unnecessary items, they ought be able to implement such an optimization utilizing such a capability in their JS respective engine.

Furthermore, we don't think such an optimization is beneficial in the world with `attributeFilter` (see the issue #367) because:
1. A custom element that doesn't use `attributeChangedCallback` should be omitting `attributeFilter`.
2. Google representatives repeatedly stated that they believe a high performance component should be doing the work (e.g. attaching shadow root) to setup itself in `attachedCallback` (see the issue #362 for the rename) instead of the constructor in which case most of custom elements would have these callback anyway.

**Comment by domenic** [comment]
I don't feel too strongly about this, and would like to defer to @esprehn and others he thinks are best to consult. But:

> This behavior precludes authors from overriding method on a particular instance of a custom element. In order to change even a single instance's behavior, you would have to define a new custom element or make the element call its own delegate method which is unnecessary boilerplate.

I think this is actually a desirable property. A given class of elements is supposed to have fixed behavior. Just like overriding `myEl.click = ...` does not change the behavior when an element is clicked, overriding `myEl.attributeChangedCallback = ...` should not change the behavior when an element is changed. Per-element runtime customization should not be a goal of custom element callbacks, IMO.

If an element is specifically designed to be extensible in this way, and have per-instance customizability, then I think an opt-in via `attributeChangedCallback(...args) { onAttributeChanged(...args) }` or similar makes a lot of sense, and doesn't count as unnecessary boilerplate.

What do you think?

**Comment by dglazkov** [comment]
The optimization will result in non-interoperable behavior: since [Get](https://tc39.github.io/ecma262/#sec-get-o-p) can have side effects, its timing is observable/actionable by developer. I could be remembering this wrong (@bzbarsky please correct me, since you pointed this out way back then).

**Comment by bzbarsky** [comment]
I believe that was the idea, yes.  We wanted the lookup of the callbacks to not be page-observable in general, which requires that it be done at a defined point in time...

**Comment by annevk** [comment]
In https://www.w3.org/2016/01/25-webapps-minutes.html, search for "on a different topic, why do we keep the callback" the motivation seems to be speed. That you don't want the set of callbacks to change over time. It's still all a little weird though, especially since a subclass will do these `[[Get]]` and such if it uses `super()`.

I don't think `[[Get]]` being observable is the problem here, since invoking the callback is already observable. And that would happen right after.

**Comment by dglazkov** [comment]
@annevk, not in the case where you apply the optimization, right? In that case, the `[[Get]` would only happen sometimes, not always.

**Comment by domenic** [comment]
@dglazkov can you define what optimization you are talking about? @rniwa seemed to be talking about an optimization that involves exchanging behind the scenes information between the JS engine and the rendering engine, which I don't think would be observable because it would never do a Get.

**Comment by dglazkov** [comment]
I apologize, I could be just not understanding this. The way I understand, the reason for perf optimization is to avoid making a `[[Get]]` just before every callback invocation. This would involve JS engine detecting when an object had change, and only doing a `[[Get]]` when both of the following is true:
1. it's time invoke the callback
2. the JS object that represents the element has changed.

When that happens, we'd do a `[[Get]]` and then store/cache it. Otherwise, we would just use the callback value, cached from the previous invocation.

**Comment by esprehn** [comment]
+1 to what domenic said, I don't think we should have to do a property lookup before every callback. Even if we could make it fast, it encourages bad behavior. Custom elements (and ES6 classes) are both about encouraging good behavior.

**Comment by rniwa** [comment]
> I apologize, I could be just not understanding this. The way I understand, the reason for perf optimization is to avoid making a [[Get]] just before every callback invocation. This would involve JS engine detecting when an object had change, and only doing a [[Get]] when both of the following is true:
> 
> it's time invoke the callback
> the JS object that represents the element has changed.

No, we would always do `[[Get]]` before invoking the callback.

What I'm suggesting is that your respective JS engine detect when the shape of the custom element instance's properties or its prototype chain and their respective properties change.  When they do, you can check whether it's possible for the element to have `attributeChangedCallback` and other lifecycle callbacks.  You can then avoid enqueuing lifecycle callbacks when the answer is definite no.

**Comment by domenic** [comment]
@rniwa, @travisleithead, @annevk, what are your thoughts on this? Did you find my argument at https://github.com/w3c/webcomponents/issues/417#issuecomment-192594110 at all compelling, that this is more of a semantic/behavioral issue than a performance issue?

@annevk regarding

> It's still all a little weird though, especially since a subclass will do these [[Get]] and such if it uses super().

while this is going to be true in general, I think a subclass that was trying to emulate the bulletproof behavior of built-ins would go a different route, and save references to `uncurryThis(ParentClass.prototype.attributeChangedCallback)` ahead of time. ([uncurryThis from here](http://wiki.ecmascript.org/doku.php?id=conventions:safe_meta_programming).) This is in general part of a large series of changes in programming style such a class would have to make, in order to go through the original operations instead of doing a [[Get]], like saving `uncurryThis(Element.prototype.getAttribute)` ahead of time and never using `this.getAttribute`.

**Comment by annevk** [comment]
I think I can live with both. I thought about it for a bit and I can't find a set of principles that supports either position very well.

**Comment by annevk** [comment]
@rniwa, @travisleithead, it's been 17 days, can you give an ETA for your response?

**Comment by rniwa** [comment]
I don't find the argument in https://github.com/w3c/webcomponents/issues/417#issuecomment-192594110 compelling.  Overriding methods on instance is something JavaScript developers regularly do, and restricting their ability to do that is rather arbitrary.

> Even if we could make it fast, it encourages bad behavior. Custom elements (and ES6 classes) are both about encouraging good behavior.

I completely disagree with that statement. [Late binding](https://en.wikipedia.org/wiki/Late_binding) and [duck typing](https://en.wikipedia.org/wiki/Duck_typing) are two important features of JavaScript.

**Comment by annevk** [comment]
@domenic perhaps you could get some insight from TC39 members this week? I think @rniwa makes some good points.

**Comment by domenic** [comment]
I brought this up at TC39 in a couple hallway discussions, and the general consensus was that although late-binding is important for things called by other developers, it's an antipattern for things called by the platform. That is why, for example, subclassing hooks in ES6 are done using late binding, but JSON parsing on the platform doesn't go through `JSON.parse` but instead uses the JSON parsing algorithm directly, and `async`/`await` does not go through `Promise.prototype.then` but uses PromisePerformThen directly, and reading data from an ArrayBuffer does not use the public `.length` property but uses [[ArrayBufferByteLength]] directly.

I think that point of view is pretty aligned with the current spec actually, and makes me even more comfortable with the current design. It not only matches the web platform (no late-binding for overriding attribute setting via changing `setAttribute`), but matches the JavaScript language design philosophy as well.

**Comment by annevk** [comment]
Fair, I would be okay with WONTFIXING this.

**Comment by travisleithead** [comment]
On Late binding of attributeChangedCallback by the user agent:
- We agree with Won't Fix because
  - It is entirely consistent with implementation principles, that the UA cache the “internal” behavior for a custom element. We are entirely in agreement with comment https://github.com/w3c/webcomponents/issues/417#issuecomment-204569197. 
  - Have a hard time understanding the use case for wanting the late binding (in particular, a custom element instance will always be created consistently first, before any of the lifecycle callbacks are invoked anyway. Conditional programming can be added to the lifecycle callbacks to workaround any limitations imposed by user agent’s caching them).
  - Makes it easier for web devs to reason about the behavior of all custom elements of a given class.
  - Are concerned about the performance impact of a late-binding for callbacks that could be invoked rather frequently (like attributeChangedCallback).

**Comment by rniwa** [comment]
I talked with people who work on our JSC engine, and they're all opposed to having this store-at-definition-time behavior.

> I brought this up at TC39 in a couple hallway discussions, and the general consensus was that although late-binding is important for things called by other developers, it's an antipattern for things called by the platform. That is why, for example, subclassing hooks in ES6 are done using late binding, but JSON parsing on the platform doesn't go through `JSON.parse` but instead uses the JSON parsing algorithm directly, and `async`/`await` does not go through `Promise.prototype.then` but uses PromisePerformThen directly, and reading data from an ArrayBuffer does not use the public `.length` property but uses [[ArrayBufferByteLength]] directly.

A better analogy would be something like [`Symbol.species`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/species) which specifies the derived object's type in builtin methods like [`map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map), and these builtin functions lookup `Symbol.species` when `map` not when class was defined.

Storing the callback object at the time of `elements.define` introduces an inconsistent behavior whereby which overriding properties on the prototype is allowed by not reflected in certain cases.

e.g.

``` js
class MyElement extends HTMLElement {
    attributeChangedCallback() {
        alert('hi');
    }
}
MyElement.prototype.attributeChangedCallback = function () { alert('(1)'); }
document.elements.define('my-element', MyElement);
var myElement = document.createElement('my-element');
MyElement.prototype.attributeChangedCallback = function () { alert('(2)'); }
Object.defineOwnProperty(myElement, 'attributeChangedCallback', function () { alert('(3)'); });
myElement.setAttribute('class', 'foo');
```

would run `alert('(1)')` because it happened before `elements.define` whereas (2) is ignored as it happens after `elements.define` is called, and `alert('(3)')` is ignored because we never run `[[Get]]` on an instance.

And the whole argument about performance is moot now because we have a mandatory `attributeFilter` which specifies what attributes are observed.  Whether `attributeChangedCallback` is present or not on the prototype doesn't really matter.

**Comment by domenic** [comment]
Telecon consensus: caching of lifecycle callbacks is the majority rough consensus; spec stays as-is.
