### ISSUE TITLE
Rename custom tag

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#434]
A tag is a bit of syntax in HTML and XML. How about "custom named element". And perhaps "custom builtin element" rather than "type extension". That way both are more clearly derived from "custom element" too.

**Comment by domenic** [comment]
I don't like these that much, but they are probably an improvement over the current... Here are my vague thoughts:
- custom named element: is this custom-named element, or custom named-element? If the latter, all elements are named, so just shorten to custom element. If the former, then it seems weird that what we're emphasizing about this element's custom-ness is its name.
- custom builtin element: Must be custom builtin-element. But that seems like an oxymoron. "builtin element customization" seems more accurate, I guess.

**Comment by annevk** [comment]
A "custom element" is either a "novel element" or an "extended-builtin element"?

**Comment by domenic** [comment]
Those I like!

**Comment by rniwa** [comment]
I don't like the term "novel". That sounds like a patent related.  How about "author-defined elements"?

**Comment by domenic** [comment]
I've never heard of a patent-related connotation for novel.

Authors prefer to be called developers. "novel element" is nice and short.

**Comment by rniwa** [comment]
https://en.wikipedia.org/wiki/Novelty_(patent)
"Novelty is a patentability requirement."

I don't think we should start calling authors as developers as the latter is ambiguous between Web developers and UA developers.  We have author defined stylesheets, UA stylesheets, etc... so that ship has sailed two decades ago.

**Comment by domenic** [comment]
I think we should avoid the whole author vs. developer debate by going with "novel element."

If you're really worried about some kind of patent thing then maybe look through the thesaurus for "novel" and choose an adjective you'd prefer to propose as an alternative.

**Comment by jaubourg** [comment]
How about "tailored element"? Makes it sound like an element that has been
tinkered with.

**Comment by jaubourg** [comment]
Also, why not "new element" rather than "novel element"? Is there something
ambiguous about "new"?

Anyway, we would have: A "custom element" is either a "new element" or a
"tailored element". Good enough?

**Comment by domenic** [comment]
I prefer novel element + extended builtin element

**Comment by rniwa** [comment]
How about "specialized element"?  I actually think "custom named element" is just fine in this context since the terminology is introduced just to distinguish type extension and regular custom elements.

Or we could just refer it to as a "custom element with its own localName".  I really dislike making up terminologies like these in general because it needlessly increases the entry barrier for casual readers.

**Comment by annevk** [comment]
@jaubourg I wanted something distinct from new since new already means creating/constructing.

**Comment by domenic** [comment]
"Novel" seems to capture the fact that these are novel element definitions not in the HTML Standard better than "specialized". And as I said, "custom named element" is not great since the name is not really what we should be emphasizing; it's the whole element that's custom.

I think it's important to have nice simple terms to refer to common concepts. That actually increases the spec's accessibility to new readers. Instead of forcing them to be reminded of minutiae like the definition of local name every time we reference something, they can simply sum up that behavior in their brain by labeling it "novel element".

I'm hoping this is not some kind of blocking issue so I plan to make the change later today after a couple meetings. I'm still willing to accept a synonym for novel if there are patent concerns. Looking through http://www.thesaurus.com/browse/novel?s=t, "original" seems OK, although maybe people would convince it with "the original list of elements already in the HTML Standard." Novel still seems best.

**Comment by jaubourg** [comment]
The only problem I have with "novel" is that it can easily bring a false
notion of innovation. If an author create a new element very similar to
what another author created in the past, it's not an innovation yet it is
still new. Same goes with original, fresh, etc sadly so maybe it's
unavoidable. I tend to prefer more neutral terms myself. Now I can surely
understand Anne's concerns about the ambiguity with creation of the actual
object.

"extended builtin" does sound like a mouthful to me. Is that supposed to
include elements that are derived from other custom elements? Like an
author creating a customization of another author's new/novel element? Or
is it specific to extending builtins?

Anyway, I don't wanna block anything, I just felt like sharing my thoughts
and give some feedback.

**Comment by annevk** [comment]
Good point about extending custom elements with is="". If that's possible it should just be "extended element".

**Comment by rniwa** [comment]
I strongly object to using the term "novel" so please don't change the spec later this afternoon.

**Comment by domenic** [comment]
Wow, really? OK. If you really want to block things I guess we'll just stick with custom tag.

**Comment by rniwa** [comment]
Yes, "novel" is a terrible word to be used in any spec without implying it's related to a patent.

**Comment by domenic** [comment]
I would suggest you consult with your team internally to find if they share your opinion that this is really an area Apple wants to block the spec on. Usually these kind of spec-internal terminology decisions are left to the editor.

**Comment by rniwa** [comment]
@domenic : I would also suggest you consult with your team whether "novel" is the best word you can come up with.  I'm fine with the current terminology (custom tag) as well.

Since this entire issue is about renaming that to use "novel element", I have to object.

**Comment by domenic** [comment]
Our team is happy to leave it up to the editor. If your team will block custom elements on this spec-internal naming issue, then that's a shame, but there's not much to do there.

**Comment by rniwa** [comment]
@domenic : There are plenty of other words in the English language.  I'm not certain why you had to pick one word that has a clear association with patents.  I'm literally fine with any other word but "novel".

**Comment by domenic** [comment]
I think the association with patents is not common. A lot of words are associated with patents, but novel is used mostly in contexts that don't have to do with patents. The legal profession repurposes a lot of words to give them special meaning but non-lawyers do not care.

See e.g. https://www.oxforddictionaries.com/us/definition/american_english/novel#nav2 (click "more example sentences").

**Comment by domenic** [comment]
I would be happy to add a _NOTE: this has nothing to do with patents_ if that would help you. (But, we would probably have to add that to a lot of words used in specs, if you have that concern, e.g. "process".)

**Comment by rniwa** [comment]
How about "regular custom element" or "ordinary custom element"?  They are really the ordinary kind of custom elements as opposed to type extension since the latter one is the odd ball here.

**Comment by annevk** [comment]
@rniwa I don't think you'll be able to find many people on this planet whose association with "novel" is "patents". That's very far from its typical meaning.

I would be okay with "regular custom element" though. Should the other be "extended custom element" then?

**Comment by jarek-foksa** [comment]
Has it been decided that "type extension elements" are actually needed?

There is no point in using a term more specific than "custom element" if there will be only one way to create custom elements.

**Comment by domenic** [comment]
Yes.

**Comment by jarek-foksa** [comment]
I'm not sure if this is up for discussion, but it feels just wrong that something like `<button is="fancy-button"></button>` is represented in DOM with inheritance rather than composition.

I would make a clear distinction between (1) custom elements and (2) mixins/traits that can be used to augment standard elements.

The current approach makes it hard to reason about custom elements and I'm afraid that introducing new terminology won't make things much simpler.

**Comment by annevk** [comment]
Please stick that in a separate issue. The new terminology proposed here is to prevent us getting stuck with bogus terminology.

**Comment by annevk** [comment]
@domenic are you okay with "regular" and "extended" from https://github.com/w3c/webcomponents/issues/434#issuecomment-196704671?

**Comment by domenic** [comment]
Not really. It's not the custom element that's being extended. Still haven't seen anything better than "novel element" and "extended-builtin element". Since this is editorial, maybe we should just handle it while merging in to HTML.

**Comment by annevk** [comment]
Well, we do classify it as a custom element by virtue of giving it the custom flag, I think. Maybe "custom regular element" and "custom builtin element".

**Comment by domenic** [comment]
What's a "regular element"?

**Comment by annevk** [comment]
Regular is there to disambiguate from custom element, which we use for either... That's it. Could also be "normal", "ordinary", ...

**Comment by domenic** [comment]
What's regular, normal, or ordinary about `<as-df>`? If anything, `<p>` sounds more regular, normal, or ordinary to me. How did we go from "novel" to "regular"?

**Comment by annevk** [comment]
Ah, "regular custom element" (`<tee-hee>`) vs "custom regular element" (`<p is=tee-hee>`).

**Comment by zcorpan** [comment]
How about "autonomous custom element"? (and "extended-builtin element")

**Comment by domenic** [comment]
I'm going to go with "customized builtin element" and "autonomous custom element". Will append a commit to https://github.com/whatwg/html/pull/1012 (and won't squash it in, so that it is clear it is a post-upstreaming change).

**Comment by epicmiller** [comment]
Jumping in late I know, but how about Original Elements and Extended Elements?

**Comment by amiller-gh** [comment]
Jumping in late I know, but what happened to discussion around `Original Custom Element` and `Extended Custom Element`? Personally, those are my favorite options so far.

Also may want to look at synonyms for "first" or "main" as antonyms for extended: http://www.thesaurus.com/browse/first, http://www.thesaurus.com/browse/main

Some more options to consider: 
- `Primary Custom Element` and  `Extended Custom Element`
- `Basic Custom Element` and `Extended Custom Element`
- `Fundamental Custom Element` and `Extended Custom Element`

**Comment by domenic** [comment]
Although those are somewhat reasonable suggestions, I'd really rather not drag out this bikeshed too long. They don't seem sufficiently better than "customized builtin element" and "autonomous custom element" to be worth the churn. Each of them has something a bit strange about them, e.g. "original custom" is kind of a contradiction, "extended custom" is inaccurate since you're not extending a custom element, "primary custom" makes it sound like there can only be one, "basic custom" sounds like it should be distinct from "advanced custom" which doesn't exist, "fundamental custom" again implies some kind of non-fundamental custom element type.

I'd like to move on.

**Comment by rniwa** [comment]
customized builtin element and autonomous custom element seem fine.  I agree we should move on since it's not like these names would be exposed to authors in any way.

**Comment by annevk** [comment]
This has been done.
