### ISSUE TITLE
Unclear on how to define :defined in CSS + HTML

### ISSUE THREAD

**Issue by domenic** [WICG/webcomponents#439]
@TabAtkins, could use your help here.

Here is what I have currently: https://w3c.github.io/webcomponents/spec/custom/#the-defined-element-pseudo-class-defined

It's pretty simple, but that's fine. What I'm confused about is how pseudo-classes get split between Selectors and HTML. E.g. compare:
- https://drafts.csswg.org/selectors-4/#enableddisabled
- https://html.spec.whatwg.org/#selector-enabled

Is the idea that we should have Selectors (or some other CSS spec) say something like

> The :defined pseudo-class represents elements that are defined as having behavior by the host language. For example, in [HTML], ...

and then in HTML we should say

> The :defined pseudo-class must match any element that is [defined](https://w3c.github.io/webcomponents/spec/custom/#dfn-defined-element)

? Is Selectors the right place for this? What heading would it go under? Maybe "Tree-Structural pseudo-classes"?

**Comment by annevk** [comment]
Maybe CSS could finally define `::backdrop` and `:fullscreen` too?

**Comment by annevk** [comment]
I don't think it matters much either way, there's no clear story here as of yet.

**Comment by tabatkins** [comment]
It doesn't matter where they live.  We move things to Selectors when they're widely applicable, but it's okay for other specs to define special-purpose things.  Like, the input pseudos can reasonably apply to host languages other than HTML.  :defined, on the other hand, is specific to Web Components.  It's _theoretically possible_ for this to be generic, but it's not something we need to worry about.

That said, your definition's markup is wrong.  It needs to be `<dfn selector>:defined</dfn>`, so it'll get picked up by Shepherd properly.  Or if you move this into HTML, `<dfn data-dfn-type=selector>:defined</dfn>`, since you can't rely on Bikeshed's markup shorthands. ^_^

If this is marked up correctly, and in a spec that Shepherd sees, it'll show up in the [CSS Index](https://drafts.csswg.org/indexes/), so we don't have to worry too much about it being hard to find.

**Comment by domenic** [comment]
Cool; I will add some data- stuff so that it stays when we move this over to HTML. It sounds like no need to split this over two specs. Thanks Tab!
