### ISSUE TITLE
Note about "custom" is misleading

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#461]
"Custom" in custom elements is defined as an element having its "custom flag" set. However, for upgrades that flag is only set together with the "defined flag". So you cannot say that a custom element becomes defined once it's upgraded, because it's only at that point that it becomes a custom element. Before that it's just an element.

We might want to have a way to refer to elements that are likely upgraded though. E.g., a "prolly-custom element".

**Comment by domenic** [comment]
I think the correct fix here is to just update the note. In particular

> As detailed elsewhere in this specification, all elements that are not custom are already defined upon their creation.

should be something like

> As detailed elsewhere in this specification, all elements that are not custom or potentially-custom are already defined upon their creation.

Maybe it would also be helpful to have examples of elements in all the possible states in the defined x custom matrix.

**Comment by domenic** [comment]
Haven't had time to work on this in detail but one thought I had is that this might be better as a tri-state "undefined", "defined", "custom" or similar. Since I don't think it's possible to have the custom flag set + the defined flag unset.

Still need to do a pass through though. Maybe we don't even need three states and can only do two.

**Comment by domenic** [comment]
Survey of current spec:
- Defined flag is only used by :defined.
- Custom flag is used by mutation algorithms. It is essentially "are there potential callbacks to call".

How these flags get manipulated:
- Failure to create an element during parsing (e.g. throwing constructor) => defined, un-custom
- Successful upgrade => defined, custom
- Create an element with a (valid) type extension: undefined, un-custom, then sync or async upgrade causes defined, custom
- Create an custom tag element: undefined, un-custom, then successful constructor or upgrade causes defined, custom
- Create a non-custom element: un-custom, un-defined if a valid custom element name, defined otherwise

Can you be custom but not defined? no.

Can you be defined but not custom? Yes:
- Failed to create an element during parsing (e.g. `<x-foo>` where `XFoo` throws).
- Not a valid custom element name, no `is=""` (e.g. just `<p>`).

---

I'm going to make two changes:
- consolidate to "custom element state" which is one of "undefined", "uncustomized", or "customized". "Defined elements" are elements in either "uncustomized" or "customized" state. "Custom elements" are elements in the "customized" state.
- Remove the special case that failing to create an element during parsing makes you defined but not custom. I think any `:not(:defined)` selectors should probably apply to such cases just fine.
