### ISSUE TITLE
Define order for attributeChangedCallback invocation?

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#474]
It's still a little unclear whether browsers are willing to converge on attribute order so maybe we should use lexicographical order here? That doesn't seem ideal though so maybe we should just hope browsers will converge on some kind of attribute order...

Copying @bzbarsky and @hsivonen since they might have opinions here.

**Comment by bzbarsky** [comment]
I need some context here.  When would attributeChangedCallback actually get invoked and under what conditions would (1) multiple attributes be involved and (2) their changes would be fundamentally unordered?

**Comment by annevk** [comment]
Basically upgrades, e.g., an `innerHTML` set or a `createElement()` call, followed by various `setAttribute()` calls, followed by `customElements.define()`, followed by insertion. I think in both cases attribute order is not guaranteed by browsers. My hope has always been that we could require logical order for the parser and insertion order for the attribute list, but there have been objections to that in the past.

**Comment by bzbarsky** [comment]
Why is attributeChangedCallback fired at all if the attrbiute are not changing _after_ the upgrade happens?

**Comment by annevk** [comment]
@bzbarsky this is so that the flow for upgrades and synchronously created elements is reasonably similar in terms of setting up the internals. Otherwise the constructor would have to iterate over the attributes and invoke attributeChangedCallback for each of them in the upgrade case (assuming you want to share that initialization code).

**Comment by bzbarsky** [comment]
Ah, I see.  In that case, seems like the order is not important, in that the custom element should be able to work with any order, right?  Almost worth specifying randomized order.

**Comment by annevk** [comment]
It should yes, my worry is that if we don't specify an order, random or lexicographical, an implementation that always has some deterministic order will end up being the one everyone has to copy.

(Maybe I should not have raised this in the hopes that such a thing occurs, so that we can then have a defined order...)

**Comment by domenic** [comment]
OK, so this is about https://w3c.github.io/webcomponents/spec/custom/#upgrades step 8 only, I believe. Currently it says "in order", because I assumed attributes were stored in the attribute list in some kind of order.

What I am hearing is that that is true, but that in the case of parser-created elements, the order is not defined? In which case, https://w3c.github.io/webcomponents/spec/custom/#parsing step 8 will also need to change.

How else is this order observable? `element.attributes`, I guess, and the new `element.getAttributeNames()`. Is there a possibility of moving the "reshuffle these in whatever implementation defined order you want" logic to `element.attributes`'s indexed getter?

If we want to have parsing use implementation-defined order for appending the attributes, but attributeChangedCallbacks be called in some order, I guess we'd need to do some weird stuff like changing https://w3c.github.io/webcomponents/spec/custom/#dfn-invoke-custom-element-actions to reorder the attributeChangedCallbacks, or maybe adding a flag to the element during parsing that causes it to do reordering during that time, but not in subsequent mutations.

This seems like a lot of mega-hacks to allow browsers to continue with implementation-defined behavior, which in general we try to eradicate. I'd prefer to not do that and just have the parser append attributes in source order. But I don't have the historical background in this issue that @annevk has.

@esprehn, @rniwa, @travisleithead, thoughts?

**Comment by bzbarsky** [comment]
It's not just the parser.  In Gecko, some attributes are shared across multiple elements, and those are stored in a separate list from the non-shared attributes; order is preserved for the non-shared attributes only.  The sharing is a huge memory and performance win, unfortunately....

**Comment by rniwa** [comment]
We have a similar memory optimization but only when the orders are the same, and that seems to work well enough for us.  It would be unfortunate if we can't agree on a deterministic ordering since that seems like an interoperability nightmare.

**Comment by domenic** [comment]
> It's not just the parser. In Gecko, some attributes are shared across multiple elements, and those are stored in a separate list from the non-shared attributes; order is preserved for the non-shared attributes only. The sharing is a huge memory and performance win, unfortunately....

So you're saying if I do `el.setAttribute("x", "x"); el.setAttribute("y", "y")` for some values of `x` and `y` Gecko will have `el.attributes[0].name === "y"`?

Does the spec currently reflect this? I can't find it. The spec appends attributes to the list, as far as I can tell, and doesn't let you insert them at arbitrary positions.

Or is there another situation, besides `setAttribute` and besides the parser, which I am not thinking of?

**Comment by travisleithead** [comment]
> It would be unfortunate if we can't agree on a deterministic ordering since that seems like an interoperability nightmare.

Wow, you guessed it. Edge is suffering that interoperability issue today, as we don't even try to preserve source order at all (we order based on a generated mapping table that changes whenever we add newly supported attributes :). We **do** have plans to fix this by switching our attribute storage system over to source-order--but it's been on our backlog for at least 5 years now. Unfortunately, it's a big change for us which is why we haven't fixed it yet.

I'd be very supportive of having attributeChangedCallback order use something natural like source order--and we'd work on getting our implementation in line with that.

**Comment by bzbarsky** [comment]
> So you're saying if I do el.setAttribute("x", "x"); el.setAttribute("y", "y") for some values of x and y Gecko will have el.attributes[0].name === "y"?

Correct.  And you're correct that the spec does not currently have any such concept; Gecko is not technically following the spec for the `setAttribute` case.

**Comment by annevk** [comment]
Based on my reading of the above I think we'd want to leave this as-is for now and hope that it sorts itself out over time.

**Comment by domenic** [comment]
Agreed. Will leave open until after the telecon in case it comes up but my guess is we'll stay the course here.

**Comment by domenic** [comment]
Telecon agreement: we will stick with the current spec, with its deterministic order. There is general agreement that we need to converge on determinism here over time, and Edge's willingness to align will be helpful in getting there. Gecko would not need to change their optimization to ship though; they can continue not being compliant for attribute ordering with hopefully minimal compat impact.
