### ISSUE TITLE
Add dispatcherEvent for callbacks

### ISSUE THREAD

**Issue by rianby64** [WICG/webcomponents#489]
Hello! I was writing a notification example, something about "submit" a form within a custom element. And I noticed that there's one case when shadowRoot is null when creating. This happen when the custom element is unresolved.

What about if add an event that will be fired when the createdCallback was called?
Check [this example](https://github.com/rianby64/proposal1/blob/master/tag-a.js#L18)

I tried to solve the problem when shadowRoot is null by dispatching my own event.
Check [this example](https://github.com/rianby64/proposal1/blob/master/tag-b.js#L27)

Hope this idea will be useful in some way.
Thanks a lot.

**Comment by andyearnshaw** [comment]
The shadow root can't be null because you're creating it right before calling `querySelector` on it in your example.  It seems more likely that `<tag-b>` isn't present in the tree.

Having a _created_ event doesn't make sense because you cannot attach an event listener to something until it's created (`createdCallback` is now the class constructor).  You might argue the case for event delegation, but it has the same issues as mutation events.  If you meant "upgraded", then you either need to dispatch an event yourself (as in your second example) or take another look at your process to see if you could do it a better way.

Ultimately, it's better left to the component developer to dispatch a _ready_ event, as there may be work that needs to be done asynchronously upon creation or an element could be created outside the document and only attached later.

**Comment by rianby64** [comment]
I didn't notice that there's a [promise](https://html.spec.whatwg.org/multipage/scripting.html#customelementsregistry) that solves my question... I'll read more about mutation events. Thanks for your advice.

**Comment by rianby64** [comment]
> _createCallback_ is now the class constructor

Then the promise mentioned above will be resolved after that function finishes its execution,  right?

**Comment by annevk** [comment]
Yeah, `whenResolved()` is the way to go.

**Comment by rianby64** [comment]
Excellent!
Custom tags are unresolved until the browser gets the correct definition to match. After that, the custom tag becomes resolved and the promise is fulfilled.
Thanks a lot, @annevk
