### ISSUE TITLE
Shadow host with its .tabindex property -1 would be skipped for focus navigation

### ISSUE THREAD

**Issue by TakayoshiKochi** [WICG/webcomponents#556]
Context:
https://github.com/w3c/webcomponents/issues/554#issuecomment-242636505

In the Shadow DOM spec 6.3
http://w3c.github.io/webcomponents/spec/shadow/#sequential-focus-navigation
specifically in Step 3.1.3, all elements with negative tabindex value will be skipped in the focus navigation, but shadow hosts with `delegatesFocus=faluse` should be excluded otherwise all focusable elements in its shadow root will never visited.

**Comment by rniwa** [comment]
@rakina : This issue seems still relevant.

**Comment by rakina** [comment]
Yes, the whole flat tree will be skipped when the host has negative tabindex value, as currently specced. Is there any interest in changing that?

**Comment by rniwa** [comment]
@rakina : I guess the users of a component decided to set `tabIndex` to be `-1` then it's probably sensible to treat it such.

I was thinking about focusing via mouse click and such but those aren't affected by this because we've isolated that to use the first focusable element in the flat tree order.

**Comment by rniwa** [comment]
@smaug---- @annevk : I think we can close this issue now. WDYT?

**Comment by smaug----** [comment]
Yes, if one uses -1 on the host, the shadow DOM shouldn't get focused. Fine to close
