### ISSUE TITLE
Is <slot> a replaced element or not?

### ISSUE THREAD

**Issue by haoqunjiang** [WICG/webcomponents#564]
[Per the WHATWG HTML Spec](https://html.spec.whatwg.org/multipage/rendering.html#flow-content-3), the `<slot>` element is listed in the section "Non-replaced elements". However, given its presentation hint (`display: contents`), it seems that `<slot>` might better be treated as a replaced element. Also Chrome 53+ seems have implemented it as such (`::before` and `::after` selectors no longer work on `<slot>`)

**Comment by annevk** [comment]
There's disagreement between WebKit and Blink as to what is correct here. @rniwa et al feel quite strongly `::before` and such should work.

**Comment by rniwa** [comment]
I think whether we treat `slot` as a replaced element is a slightly orthogonal issue to whether it has `display: contents` as the style or not.  Having said that, `slot` is kind of special since its content is the slotted nodes so I could see it being treated as a replaced element.  Really though, `slot` is a special element different from replaced or non-replaced element.

**Comment by hayatoito** [comment]
When users specify an author rule, `slot { display: block }`, I would like `<slot>` to behave like a `<div>`, in terms of layout.
Though other nodes are assigned to _children_ of a slot in the layout tree, there should be no difference between `<slot>` and `<div>`, other than that, in this case.

Does it mean `<slot>` is NOT a replaced element?

I do not fully understand the impact of letting it being a replaced element. What is a user visible impact?
`::before` (or `::after`) can not be applied for a replaced element, per the spec?

**Comment by haoqunjiang** [comment]
@hayatoito It's stated in [CSS Generated Content Module Level 3](https://www.w3.org/TR/css-content-3/#issue-7255651b):

> Replaced elements do not have '::before' and '::after' pseudo-elements

**Comment by hayatoito** [comment]
Thanks! Then, I propose the status quo;  `<slot>` should be a Non-replaced element.

Regarding the current behavior in Blink, please do not take it seriously. No explicit intention there.
The current support of `<slot>` in Blink is incomplete because Blink does not support "slot" in a flat tree.
See https://github.com/w3c/webcomponents/issues/308 for details. Blink does not create any layout box for a slot, as of now.

**Comment by hayatoito** [comment]
Let me close this with status quo since this issue did not get the attention.
