### ISSUE TITLE
Status codes for HTML Imports

### ISSUE THREAD

**Issue by tomalec** [WICG/webcomponents#568]
As I posted already at https://github.com/w3c/uievents/issues/92, but I think it gets more meaning for HTML Imports/Modules

Currently, `onload` event of `<link rel="import">` does not provide any information on status code.
I don't see a reason for not to adding it for example to `event.detail`.
It would increase variety of use cases and give more control to HTML Imports created problematically.

**Comment by domenic** [comment]
This doesn't really seem related to HTML imports or modules, but instead to all the load events on the platform. `<link rel="import">` will probably not be in the final form of HTML modules, but if it were, this would be a question about `<link>` in general, not about `rel="import"` specifically.

In general the platform has gone with an approach where an [ok status](https://fetch.spec.whatwg.org/#ok-status) generates a load event, and a network error or non-ok status generates an "error" event. Why is distinguishing between the different OK statuses important for your use case? For GETs, the only possibly-useful ones I can see are 200, 203, 204, maybe 205. Can you describe an application in more detail that would make use of the distinction between these status codes?

Remember that we don't add features because there's no reason for not adding them. We add them based on consideration of use cases which cannot be accomplished any other way. See also https://wiki.whatwg.org/wiki/FAQ#Is_there_a_process_for_adding_new_features_to_a_specification.3F for tips on describing your use case independent of your solution.

**Comment by tomalec** [comment]
Sorry, for not following the process.

My main use case is that, I build HTML partial/include system on top of HTML Imports (http://starcounter.io/html-partialsincludes-webcomponents-way/ we already have at least 4 other companies running that pattern).
1. I import HTML document on fly by custom element (by appending `<link rel="import">`) 
2. If it arrives successfully 200 I stamp `<template>` from inside into the main document - 
   
   > thanks to that all HTML Import driven or script driven depenencies in structured, well defined and consistent manner, while still being able to run inline scripts from within template, or use external document to prepare template.
3. then do some data-binding, theming, and layout management work on top of what comes

If for some reason server-side simply does not have content, I'd like to send it with 204, and let the custom element could notify author  about the reason his/hers screen looks blank. Also the custom element element will not do any decoration or data binding work on top of that.

Currently, if file served is just empty, `.linkElement.import` still becomes a Document, so I need to check `document.body.children.length === 0 && document.head.children.length === 0` (what loos to me like a hack).

Moreover, it would be great to be able to use the difference between 204 and 205.

Current HTML Imports serves great for partials, so it would be great to get support for similar use-cases with new spec.

**Comment by domenic** [comment]
I think the best way to detect whether there's no content is to do exactly what you're doing: check that there's no content. It's not a hack.

**Comment by TakayoshiKochi** [comment]
As domenic@ already commented, this looks not specific to HTML Imports (or future modules), and is already proposed at https://github.com/w3c/uievents/issues/92.

Let me close this issue as we do not spend time on HTML Imports moving forward.
