### ISSUE TITLE
Overwrites geter/seter in class CustomElement

### ISSUE THREAD

**Issue by ParkFramework** [WICG/webcomponents#598]
Is bug?

``` HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
</head>
<body>

<my-custom-tag></my-custom-tag>

<script>

    'use strict';

    document.querySelector('my-custom-tag').data = 'BUG';

    class MyCustomTag extends HTMLElement {
        constructor(...args) {
            super(...args);

            this.innerHTML = this.data;
        }

        get data() {
            return 'OK';
        }

        set data(value) {
        }
    }

    customElements.define('my-custom-tag', MyCustomTag);

</script>
</body>
</html>
```

**Comment by annevk** [comment]
What exactly is it that you think is a "BUG"?

**Comment by matthewp** [comment]
The getter/setter is still there on the prototype, check `this.__proto__.data`. You could presumably correct for pre-upgrade values in your constructor by deleting the existing values.

Btw, your setter has a bug that will cause infinite recursion.

**Comment by ParkFramework** [comment]
> Btw, your setter has a bug that will cause infinite recursion.

Fixed :)

> What exactly is it that you think is a "BUG"?

Do you think that we should always do so in the constructor?

``` JS
    document.querySelector('my-custom-tag').data = 'PayLoad'

    class MyCustomTag extends HTMLElement {
        constructor(...args) {
            super(...args);

            if(this.data !== this.__proto__.data) {
                let data = this.data;

                delete(this.data);

                this.data = data;
            }

            this.innerHTML = this.data;
        }

        get data() {
            return this._data;
        }

        set data(value) {
            this._data = value
        }
    }

    customElements.define('my-custom-tag', MyCustomTag);

```

I would like to object instance node, could not override the API prototype.

**Comment by annevk** [comment]
This is just how classes work. If you want to change how classes work, best to talk to TC39.

**Comment by matthewp** [comment]
@annevk I can't think of another scenario where an object has a property before its proto is set.  I tried recreating this scenario with normal classes and failed.  Which is not to say that anything needs to be changed here, just that upgrades are somewhat different and this bears being explained for web developers. Perhaps MDN is a better place for that than here in the spec though.

**Comment by WebReflection** [comment]
@matthewp the problem is that in your case the element gets promoted. This is, metaphorically speaking, the equivalent of the following:

``` js
var obj = {data: 'BUG'};

// redundant extends here
// it's only to explain the metaphoric case
function MyObj() {
  Object.call(this); // super()
  console.log(this.data);
}

Object.defineProperty(
  MyObj.prototype,
  'data',
  {get: function () { return 'OK'; }}
);

// when a custom element is defined
// elements that reflect its definition
// will be promoted in a similar fashion

// upgrade the prototype
Object.setPrototypeOf(obj, MyObj.prototype);

// and execute the constructor (+ super call)
MyObj.call(obj); // BUG

// but new instances ...
new MyObj(); // OK
```

**Why is that?**

The previously defined `data` property is **own**, and own properties shadow inherited properties.

Custom elements can be defined in the future, but until that moment, if you have them already in the page, or you create them in some other way, these acts exactly like any other regular `HTMLElement` would.

The moment they get promoted, passing through the constructor, is the moment they could have own properties able to shadow inherited one, like in your case.

There's no way to change this behavior because there's no way we want to lose the ability to define in a non blocking way with asynchronous promotion Custom Elements.

**Comment by ParkFramework** [comment]
I know how it works, thanks. 👍 

But I think it's a bug, because the behavior is not in harmony with the attributes of behavior.
Here is the right behavior:

``` HTML
<!DOCTYPE html>
<html lang="ru"><head>
    <meta charset="UTF-8">
</head>
<body>

<my-custom-tag data="NoBug"></my-custom-tag>

<script>
    'use strict';

    class MyCustomTag extends HTMLElement
    {
        constructor(...args)
        {
            super(...args);
        }

        static get observedAttributes() { return ['data']; }

        attributeChangedCallback(name, oldValue, newValue)
        {
            this.innerHTML = `Yes, ${newValue}.`;
        }

    }

    customElements.define('my-custom-tag', MyCustomTag);

</script>

</body>
</html>
```

**Comment by WebReflection** [comment]
> Here is the right behavior:

that's just a whole different story, since you moved your expectations out of the constructor and delegated to the `attributeChangedCallback` event + you dropped the getter, which wouldn't be influenced anyway by attributes.

So, to be fair, you didnt use direct property assignment upfront, and you used HTML and an attribute, so basically you replicated two completely different scenarios but you stated you know how it works.

I leave you believing that, but I'm not 100% sure you do.
