### ISSUE TITLE
Can't reuse custom element constructors?

### ISSUE THREAD

**Issue by bicknellr** [WICG/webcomponents#618]
https://html.spec.whatwg.org/#element-definition
Step 4: If this CustomElementRegistry contains an entry with constructor *constructor*, then throw a "NotSupportedError" DOMException and abort these steps.

This restriction seems a bit arbitrary. Any reason it was added?

**Comment by domenic** [comment]
If you registered `X` under two different names, then did `const x = new X()`, what would `x.localName` be?

**Comment by rniwa** [comment]
This is why we proposed to make the first argument of each constructor the local name but since we’re not doing that in v1 API, this would indeed becomes an issue.

In the prototype I implemented, I made this constructor argument optional so that if a constructor defined exactly one custom element, it would be omitted.  We could go on that route still since that would be backwards compatible.

**Comment by bicknellr** [comment]
Oh, good point, I hadn't thought about `localName`... If you all want to close this, feel free.

**Comment by bicknellr** [comment]
Maybe `localName`'s getter could look up its own constructor in the registry?

**Comment by rniwa** [comment]
@bicknellr : Then find what? The problem is that if a constructor X is registered as elements E1 and E2, then `new X` must construct either E1 or E2.  Who/what decides that?

**Comment by bicknellr** [comment]
Yeah, it wouldn't help with the one-to-one mapping everywhere that's currently implied by the global registry. It would be nice if there was still the possibility of scoped local names amongst documents - or maybe their associated DOMParser instances, if there were such a thing - but that's a totally different topic.

**Comment by rniwa** [comment]
A local registry would require a custom element’s constructor identifying itself to `HTMLElement`’s constructor as to which registry it belongs. e.g. new argument.  Alternatively, we need to introduce a new internal slot in ECMAScript like `new.target` which corresponds to this extra information.

**Comment by treshugart** [comment]
There was [some discussion in a separate issue](https://github.com/w3c/webcomponents/issues/509#issuecomment-230703725) about the ambiguity of having the same constructor used for different elements being something that should be moved away from.

It was in reference to how it'd be nice to be able to infer the customised built-in using the extended HTML element, such as `HTMLParagraphElement` - instead of using the `is` attribute. However, this is *not* possible across the board because `HTMLQuoteElement` serves both `<blockquote>` and `<q>`, so there's no way to actually tell which one the custom element author wanted to customise. If the spec were to allow for the same constructor to be used for multiple custom elements, this would perpetuate that problem.

I don't see much of an issue with this as you can just do the following:

```js
class A extends HTMLElement {}
class B extends A {}

customElements.define('x-a', A);
customElements.define('x-b', B);
```

**Comment by WebReflection** [comment]
In a parallel universe, where extending natives different from `HTMLElement` is already possible:
```js
class CustomQuoteElement extends HTMLQuoteElement {
  /* common implementation / overrides */
}
class CustomBlockquote extends CustomQuoteElement {}
class CustomQ extends CustomQuoteElement {}

customElements.define('custom-bq', CustomBlockquote);
customElements.define('custom-q', CustomQ);
```
If that was possible, let's say like it is already through `is="" mechanism`, I don't see any ambiguity or limitation.
