### ISSUE TITLE
Custom 'void' or self-closing elements (HTML parser changes)

### ISSUE THREAD

**Issue by pfrazee** [WICG/webcomponents#624]
This was discussed in https://github.com/w3c/webcomponents/issues/113

It would be very nice to be able to declare Custom Elements as void or self-closing. Given that element names are already a little lengthy (from the required dash) there are times where avoiding the name repetition would preferable.

Presently, all custom elements must be used as:

```html
<my-element></my-element>
```

And I'd like to be able to do self-closing:

```html
<my-element />
```

Or void:

```html
<my-element>
```

Perhaps by a static getter in the class definition

```js
customElements.define('my-element', class extends HTMLElement {
  static get isVoid() { return true }
})
```

Any chance we can reopen this discussion?

**Comment by rniwa** [comment]
This would require a HTML parser change. We might be able to do this (self-closing) if we restricted to elements with `-` in its name.

**Comment by annevk** [comment]
Nobody wanted to change the HTML parser the last time around. What changed?

**Comment by rniwa** [comment]
Well, I didn't want a parser change to be part of v1 since that would have required a lot more compatibility checks. Now that v1 is out the door, I think it might be worth checking whether there is an actual Web compatibility issue or not.

**Comment by annevk** [comment]
@rniwa https://github.com/whatwg/html/issues/919#issuecomment-276329905 has pretty good rationale for why we nevertheless probably shouldn't do it.

**Comment by pfrazee** [comment]
That's a credible reason, so the question is, how much do we care about self-closing tags? Enough to fight that battle?

App devs can work around this using custom templating engines, but that's a shame when you consider that part of the appeal of Custom Elements is getting away from non-native solutions.

**Comment by Jamesernator** [comment]
I would definitely like to see self-closing tags, a good amount of tags I've found useful can be often described from their attributes e.g. `<x-markdown src="./some-info.md"></x-markdown>` which would be a lot nicer as just `<x-markdown src="./some-info.md" />`.

**Comment by rniwa** [comment]
@annevk I don't agree with @hsivonen assertion that we should not make changes to the parser. There are many things that are security sensitive. In theory, the security of websites can rely on the absence of any Web feature and become vulnerable when any new feature is introduced. But we don't stop introducing new features just because of such a concern. I can be convinced if this turns out a be real security concern, but given the importance of the motivating use cases, I'm not at all convinced we can't make any changes here.

**Comment by Jamesernator** [comment]
@rniwa Yeah I don't think the argument is strong enough to suggest that we should never change the parser ever and stop adding features to html. By the html definition `<x-markdown />` should be an error anyway even though browsers recover and wrap following content in it.

It's weird too because the html document even specifies that [tags from other namespaces can be self-closing](https://www.w3.org/TR/html5/syntax.html#start-tags), it just seems weirdly inconsistent. Is there a particular reason *every* element can't be self-closed?

**Comment by annevk** [comment]
@rniwa I still don't see how minor changes here and there to the HTML parser actually accomplishes what folks want, which is custom elements that can take the place of arbitrary HTML elements, such as `<li>` or `<td>`. And what it does do is make the HTML parser less reliable and a source of bugs and problems across the ecosystem.

**Comment by Jamesernator** [comment]
@annevk Just speaking for myself but I'm sure others would like it too but I'd certainly find self-closing tags an improvement and assuming only `<x-foo />` form is allowed (initially at least) it shouldn't conflict with `<p>` like behaviours which I feel should be a separate issue given that it's far more complicated.

And from what I'm aware isn't it the case that a correct parser should consider this an error anyway `<x-markdown />` (assuming this still applies https://www.w3.org/wiki/Validating_your_HTML#Different_browsers_interpret_invalid_HTML_differently) so correct parsers shouldn't break (just fail) if given `<x-markdown />`, the thing is the addition of virtually anything to HTML could potentially make the HTML parser a source of bugs, e.g. simply adding another void tag or auto-closing (like `<p>`) (and plenty of other things I'm sure) would mean existing parsers would be invalid . For those reasons I'm definitely not happy with the argument that we can't extend HTML because some parsers might break.

**Comment by annevk** [comment]
@Jamesernator HTML parsers do not fail and that document seems out-of-date at best. The HTML parser we care about is defined at https://html.spec.whatwg.org/multipage/syntax.html#parsing and any change would have to be a change to that algorithm.

**Comment by annevk** [comment]
There's no interest in changing the HTML parser for void elements. The bar for changes is too high and the ergonomic benefit is too low.

**Comment by abitrolly** [comment]
Just to clarify - there are these two types of elements:
1. void - `<my-element>`
2. self-closing - `<my-element/>`

It seems logical that modifying parser to catch new void elements is not good, because nobody knows if custom element should be void or not just by looking at the tag. But what is the problem with self-closing tags?

**Comment by annevk** [comment]
I should have been more clear, my statement applies to self-closing tags too.

**Comment by abitrolly** [comment]
Then how high would be the bar for changes if we concentrate only on self-closing tags without touching void elements?

**Comment by annevk** [comment]
It's still too high. There's basically only interest in security fixes and non-normative changes.

**Comment by abitrolly** [comment]
So people are doomed to double their simple `<custom-element></custom-element>` names till the end of internet?

**Comment by annevk** [comment]
As far as the `text/html` format goes that's where we're at.

**Comment by amkuipers** [comment]
as a developer using custom elements I would really like self-closing custom elements. It makes no sense to me if I have a `<custom-box color='RED' />` , that my browser even stops and ignores the remaining html code. I must specify a separate closing tag for the custom-box before it even works. 

- Developer friendly: allow self-closing custom elements for custom element users

Another motivation is; when someone is using the custom element and that element has no nested content or elements, that developer wants to cleanup its code by changing it to a self closing element. It just looks ugly.

Another motivation is; when the custom element needs a separate closing element, the developer might assume that the custom element accepts content; which it might not. 

 - I would vote for the custom element IDE to issue a warning on ignored content for:
```

<custom-box color="RED">ignored text</custom-box>
<custom-box color="RED"><p>ignored child element with text</p></custom-box>

```

**Comment by ivands** [comment]
Thumbs up for self-closing tags.
Let's move forward and make the web a better developer experience.

**Comment by pvh** [comment]
This is surprising and really unfortunate behaviour. It also doesn't produce any obvious errors unless you inspect the output DOM.

**Comment by thomas-darling** [comment]
> https://github.com/w3c/webcomponents/issues/624#issuecomment-385341368
> ... There's basically only interest in security fixes and non-normative changes.

> https://github.com/w3c/webcomponents/issues/624#issuecomment-385347171
> So people are doomed to double their simple `<custom-element></custom-element>` names till the end of internet?

> https://github.com/w3c/webcomponents/issues/624#issuecomment-385356383
> As far as the `text/html` format goes that's where we're at.

@annevk Sorry, but I simply cannot accept this.

This is a very real problem for those of us who write large web apps, and something that causes quite a bit of daily frustration, wasted time, and bloated code.

The ergonomics of a language matters, and saying we just have to live with it because you do not feel like _ever_ evolving the language in any way, that's just plain unacceptable to me.

Please either provide a valid reason why `<foo/>`, which as I understand it is currently invalid, can't simply be interpreted as `<foo></foo>` - or reopen this issue so we can have some actual progress.

**Comment by pvh** [comment]
Hi @thomas-darling, as a fellow commenter and person also disappointed by the position taken here I just wanted to encourage you to apologize for writing to the project maintainers the way you just did.

The work these people do is difficult and involves trading off a great many factors for an audience of billions. As (I assume) you don't employ anyone else here, you don't have the right to demand work or outcomes from them. If you did work with these people, I hope you'd have the good manners never to speak to your colleagues that way.

Further, this kind of attitude is simply self-defeating. Nobody wants to help a jerk, and treating maintainers this way will only predispose them against your positions.

If you want someone to change their mind, you should try convincing them instead of telling them they're wrong. (One way to convince someone is to have many people politely offer a dissenting opinion, which is what I attempted.)

**Comment by pfrazee** [comment]
Let's pause the conversation about etiquette, just to keep the conversation on track.

I would very much like for this issue to be revisited. @annevk who could we lobby to make this change happen? If we had some idea of the WGs or teams to discuss this with, I'm sure there are plenty of people here who'd be interested in making our case to those people.

**Comment by annevk** [comment]
Ultimately, you'd need to convince browsers to change their HTML parser. As I alluded to above, that seems unlikely to happen, but you're welcome to try again.

As an alternative I've been wondering if we should revive "[XML5](https://annevankesteren.nl/2007/10/xml5)", which would allow for solving this problem, as well as declarative shadow trees. Unfortunately there's not much appetite for that either. At least so far.

**Comment by andreasplesch** [comment]
Let me add the specific example of [A-Frame](https://aframe.io/docs/0.9.0/introduction/html-and-primitives.html) - a large Mozilla effort using custom elements which would benefit quite substantially from self-closing tags since all content is in attributes.

Related, but somewhat off-topic, is the use of Unknown Elements to carry meta-information (`<databasefield name='partID' value='xyz' />`), or in custom extensions.

**Comment by vectorjohn** [comment]
This may not matter, since it's browser vendors that need convincing, but it really makes no sense not to allow any tag to self close. Its semantically and unambiguously equivalent to spelling out the whole close tag.

Arguments about ergonomics or "writing big apps" aside (they don't convince me, that's just wishy washy), the real reason in my opinion for self closing tags is they communicate intent better than not having them. When making a custom component for which nested content will never make sense, it's a bad idea to have markup that kind of sort of implies that it might do something. It's just another place for errors. A self closing tag means "the child content of this element is meaningless, and should even be considered an error". You need look no further than the humble meta tag. Why would the interface want to *imply* that it might mean something to write `<meta>hello</meta>`? I suppose component authors can do runtime checks to validate things like that. 

On the other hand, to me it doesn't matter that much either way. It just seems like such a trivially silly thing to have in the html5 spec.

**Comment by abitrolly** [comment]
The problem with this specific issue is that it mixes **custom void**
elements and **custom self-closing** elements. The issue should be split it
two, because the main argument against here is difficulty of parser
modification, and the modification varies greatly between:

1. - void elements - <my-element> - for which parser modification is hard,
because it requires tracking the type of the tag and potential content
inside
2. - self-closing - <my-element/> - parser modification is easy requires,
because it only requires tracking of the closing sequence **/>**

Other consideration is that HTML parser is HTML aware and should not be
treating <p> and legacy elements the same way as custom elements, so the
legacy elements should be out of scope as well.

**Comment by pfrazee** [comment]
Don't know about everybody else, but I would gladly take self-closing elements as a solution to this.

**Comment by pvh** [comment]
Absolutely. I was only frustrated by the lack of self-closing custom elements and have no interest in custom void elements.

**Comment by rniwa** [comment]
Note that either support self-closing or void elements DO require a parser change. The cost isn't so much about updating the parser but it's that every HTML parser implementation in the world would have to update the parser or else we'd get XSS vulnerability everywhere :( Not saying it's impossible or it's a bad idea but the cost isn't just in the web browser but everything that touches the HTML content in general.

**Comment by alshdavid** [comment]
I don't care about custom void elements, but custom self closing elements would be incredible.

Imagine

```html
<fa-icon style="solid" type="cross" />
```

**Comment by thomas-darling** [comment]
@rniwa
Could you, or someone else, please explain how adding support for self-closing elements, i.e. `<foo/>`,  would actually introduce an XSS vulnerability? - preferably with an example.

Maybe I'm missing something, but I don't see a problem here - and I'm probably not alone  :-)

**Comment by mutech** [comment]
I think this is a perfect illustration of why some of HTML5's specs are grandiosely bad.

Specifying that some specific elements may be void or self-closing is objectively stupid. It makes parsing more difficult, it is confusing for authors and the benefit is minuscule and a matter of taste.

If HTML had left self-closing tags as transparent equivalent to empty tags (from XHTML), this issue would be non-existent and there is practically no penalty at all for the parser and users who like closing elements can continue to use them.

Void elements have a small benefit for authors using vi and make parsing difficult. For backward compatibility, they should have been deprecated. 

These bad decisions (along with removing namespaces in some places and keeping them elsewhere) will keep haunting us for many decades.

I don't think that it is really important that custom elements can specify how they should be parsed, but I think it is important that custom element do not have to specify that.

**Comment by Rob-pw** [comment]
I understand this isn't feasible, but for whatever reason should it one day be possible in the future.

**Comment by dy** [comment]
[@annevk, W3C](https://github.com/w3c/webcomponents/issues/624#issuecomment-370310607):
> There's no interest in changing the HTML parser for void (self-closing) elements. The bar for changes is too high and the ergonomic benefit is too low.

Also [W3C](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies):
> In case of conflict, consider users over authors over implementors over specifiers over theoretical purity.

@rniwa, regarding _every HTML parser implementation in the world would have to update_ - isn't that the case of the HTML design principle above?

**Comment by trusktr** [comment]
> As I alluded to above, that seems unlikely to happen, but you're welcome to try again.

@annevk Perhaps the issue should be re-opened so we can continue trying.

Can someone link to the XSS vulnerabilities?

Is it possible to have a new space to work in, with new parsing rules without the error-guessing semantics or special tree mangling rules? ⚡

```html
<html ⚡></html>
```

The following would be valid:

```html
<html ⚡>
  <script src="foo.js" />
  <div class="single-div-challenge" />
  <gltf-model src="path/to/helmet.gltf" />
</html>
```

There would be _no void elements_. Only `<foo></foo>` and `<foo />`. But I suppose this means stuff can not appear on screen as soon as possible, because closing tags need to be found. We can make an exception: The closing `</html>` tag is inserted after the first piece of incorrect markup is removed, and no more markup is loaded, and an error is output to console.

Based on this idea, if we write

```html
<html ⚡>
  <script src="foo.js" />
  <div>
    <gltf-model src="path/to/helmet.gltf">
  </div> <!-- error thrown at this point -->
  <img src="..." />
</html>
```

The result may be the same as the following HTML from today:

```html
<html>
  <script src="foo.js"></script>
  <div> </div>
  <img src="..." />
</html>
```

If we write

```html
<html ⚡>
  <script src="foo.js" />
  <div>
    <div>
    <gltf-model src="path/to/helmet.gltf">
  </div> <!-- error thrown at this point -->
  <img src="..." />
</html> <!-- error thrown at this point -->
```

The result may be as if we wrote

```html
<html>
  <script src="foo.js"></script>
</html>
```

The only special mangling rules would be the automatic addition of `<body>`. Beyond that, all else would be what-you-write-is-what-you-get, or parser would need to abort with an error.

So this,

```html
<html ⚡>
  <p><div /></p>
</html>
```

could either result in an `HTMLParagraphElement` having an `HTMLDivElement` child, which is something we can do when we create a tree with imperative JavaScript, or it would throw a parser error (instead of mangling).

Or we update `HTMLParagraphElement`'s implementation so that it actually calls `removeChild` on any element at runtime (triggering MutationObserver and custom element life cycles) rather than it being parser magic.

If `<p><div /></p>` would make a parser error and stop the parsing, then

```html
<html ⚡>
  <div>
    <p><div /></p>
  </div>
  <img />
</html>
```

would either be like writing

```html
<html>
</html>
```

or parsing errors could be localized to the smallest known error area, in which case the last result would instead be

```html
<html>
  <div> </div>
  <img />
</html>
```

Basically in that last case, after removing/ignoring the bad `<p><div /></p>` and throwing an error to devtools console, the parser would continue to see if it can continue without the known-bad piece (as if we never wrote it).

Some elements should always be self closing, and the parser should error when they are not.

For Custom Elements, which may be defined later after parsing, maybe there's no enforcement. Or maybe there's a way to map custom element names to booleans indicating if they should be self-closing or not (perhaps like `script type=selfclosingtags` that is lighter-weight than JS, and actual `customElements.define` calls can happen later?).

---

We need self-closing abilities for all elements, and void elements are just a source of ambiguity (elements either have children, or they don't). 

## Be gone void elements! :ghost:

The vast majority of libraries and frameworks (every one that I have ever tried) does not accept void elements, and treats them as errors. 


JSX is fairly popular (used in React, Preact, Solid.js, Surplus, and a bunch more) and it is an error to write a void tag in JSX.

Vue, Angular, Svelte all throw errors on void elements.

This equates to every major framework disallowing void elements.

Clearly people don't want the ambiguity from void elements.

If ignoring void elements helps to make all tags self-closeable, let's do it.

**Comment by Jamesernator** [comment]
> This would require that custom element definitions happen in a script tag before any custom elements are encountered during parsing

Parser blocking on scripts is always fairly expensive, this is why new features (e.g. module scripts) don't allow it, and there's even features in the works specifically to disable the behaviour entirely (e.g. [feature policy](https://chromestatus.com/feature/6218263637786624)).

Anything that requires new sync scripts is almost certainly not going to gain any implementer interest.

A warning *after the fact* might be viable, as browsers could simply set a bit while parsing and then check and warn during upgrade.

**Comment by trusktr** [comment]
Good point. I felt iffy writing it; knew someone would mention it. 

I believe in my personal cases it would be fine (I would prefer to focus on making a pleasant loading experience with off-main-thread CSS animation). And with a custom-element-heavy applications, the experience may be no good without the JS anyway.

I updated it to replace that part with a shorter simpler idea.

**Comment by ghost** [comment]
@trusktr: Although I don’t think your specific idea is easily feasible (and also, I don’t think preventing elements like `<meta>`, `<link>`, `<br>` from having self‐closing or void tags actually helps with anything at all), I do agree that it makes sense to wish for a fresh new HTML parsing mode that removes certain struggles from authors. Anne’s “XML 5” idea seems like a more sensible approach.

On the other hand, however, I really don’t think it’s actually going to happen any time soon, if ever at all. It seems that implementors are consistently really sceptical of changing parser behavior, mostly because of difficult security analysis that needs to be made on their implementations.

In addition, of course, is the very difficult implied questions of “What about APIs such as `.innerHTML`?” Should those APIs keep the old parser behavior, or should they reflect the new parser mode? Note that a lot of existing libraries might expect the old parser behavior, and break (perhaps in subtle ways) if it’s different.

There is very little ergonomic benefit in changing the parser now, compared to all the potential problems and questions that arrive from it.

**Comment by abitrolly** [comment]
And here is the link to HTML design documents and specifically to `Priority of Constituencies` which is broken by reasons given by @annevk for closing this issue.

 https://www.w3.org/TR/html-design-principles/#priority-of-constituencies

> ### 3.2. Priority of Constituencies
> 
> In case of conflict, consider users over authors over implementors over specifiers over theoretical purity. In other words costs or difficulties to the user should be given more weight than costs to authors; which in turn should be given more weight than costs to implementors; which should be given more weight than costs to authors of the spec itself, which should be given more weight than those proposing changes for theoretical reasons alone. Of course, it is preferred to make things better for multiple constituencies at once.

**Comment by ghost** [comment]
Since this is the second time this same statement has been brought up in this issue, I wanted to mention that no‐one seriously cares about that document, at least not since 2007, when the document was last updated.

It’s not an unreasonable statement, but over time, people have come to realize that it doesn’t actually work well (for the Web, at least). It doesn’t really matter if “authors really want it”, if implementors don’t implement it, either because they can’t or because they don’t want to, the specification becomes moot, as a series of problems arrive.

If the spec is implemented inaccurately in ways that leave discrepancies between it and implementations (in incompatible ways), new implementations won’t want to follow it and risk breaking existing websites. They will prefer to try to copy the behavior of existing implementations, and that opens the opportunity to the implementations themselves to differ. (Which is exactly what the spec is trying to avoid!)

Also note that whatever merit that the aforementioned “Priority of Constituencies” paragraph has is limited to *making decisions*, not *changing them*. In this case, the decision of “not allowing either void or self‐closing custom elements” was already made implicitly when custom elements were specified without it. Changing that *now* has different implications than when it was first specified.

**Comment by WaltzingPenguin** [comment]
Not being able to make custom elements self closing starts to introduce some serious room for error when dealing with slots.

This renders the default content of the slot:
```<my-element></my-element>```

This renders the slot as empty (replaced with whitespace):
```<my-element> </my-element>```

The difference between the two is easy to miss and is problematic, _especially_ when distributing components to outside users. `<my-element />` would be much clearer.

**Comment by rob2d** [comment]
It's mainly a matter of making things idiomatic for humans; Like any code, but especially a declarative templating system, HTML shouldn't be meant to just be written but to be read since it's basically a templating language (obviously there is more into that like reliance on DOM; but the XML semantics weren't just a coincidence/side effect of the functionality).

Been working with building components in a custom Web Component library for the past few months and in terms of interfaces it has been a little bit redundant with this aspect and it's hard to make an interface that is more pleasant as there has to be an extra level of consideration trading off the name specificity of a simple custom element ; with web components you need to repeat everything 2x even if it is a simple or self-contained. Issue is especially obvious with web components when you consider slotted vs not slotted elements, and matters where users might either need to nest content or not.

I can't make pretend personally that it would be painless for browser engines to do this, and I definitely respect the work of these developers, but semantic issues like this in 2021 should probably be a relative priority if web components are at least aiming to make things more idiomatic or succinct /jmho.

**Comment by besworks** [comment]
I came up with [a technique](https://jsfiddle.net/f92jgc7a/3/) to work around the behavior that @WaltzingPenguin mentioned a few comments up. Basically, just check if the element contains **only text nodes** that contain **only whitespace** and if so purge them all. Do this in `connectedCallback` and any time nodes are added to or removed from the host with a `MutationObserver`.

**Comment by taburetkin** [comment]
i found this thread because i tired to write in my html `<my-component></my-component>` again and again
so i started to look for solution for this.

imo the void elements by itself are evil and implies *to know* all the void elements.
If you are not aware of all void elements this `<br><hr>...` will be not self explanatory.

everything would be much simpler if there were no void elements at all, if all containers always looked like this `<xxx></xxx>`, and all elements without children like this `<xxx />`

**Comment by andyearnshaw** [comment]
@taburetkin, you could achieve that by writing your pages using _XML syntax for HTML_ (formerly referred to as "XHTML"):

> The second concrete syntax is XML. When a document is transmitted with an [XML MIME type](https://mimesniff.spec.whatwg.org/#xml-mime-type), such as [application/xhtml+xml](https://html.spec.whatwg.org/multipage/iana.html#application/xhtml+xml), then it is treated as an XML document by web browsers, to be parsed by an XML processor. Authors are reminded that the processing for XML and HTML differs; in particular, even minor syntax errors will prevent a document labeled as XML from being rendered fully, whereas they would be ignored in the HTML syntax.

https://html.spec.whatwg.org/multipage/introduction.html#html-vs-xhtml

**Comment by abitrolly** [comment]
@andyearnshaw the advice to use XHTML looks like [banana and gorilla](https://www.johndcook.com/blog/2011/07/19/you-wanted-banana/) to me.

**Comment by andyearnshaw** [comment]
@abitrolly, I'm not advising to use XHTML; I don't use it myself. I'm saying that, if a super-strict, no-void-elements parser is required, one already exists. Someone thinking about using XML syntaxt for HTML would need to consider the benefits/drawbacks for themselves. 

While I agree with the sentiment that "everything would be much simpler if there were no void elements", that ship has sailed for HTML (it left the dock about 30 years ago).

**Comment by abitrolly** [comment]
@andyearnshaw I doubt that a person tells who tired of writing `<my-component></my-component>` wants to deal with additional limitations imposed by super-strict XHTML toolchain.

> While I agree with the sentiment that "everything would be much simpler if there were no void elements", that ship has sailed for HTML (it left the dock about 30 years ago).

Can you remind me again, why it is impossible for ships to return to dock for retrofitting?

**Comment by Danny-Engelman** [comment]
HTML was and never will be retrofitted.
This discussion was closed 6 years ago in 2017
There will never be self-closing custom elements. 
Period.

<s>If you don't understand Why, you will find a better career flipping burgers at McDonalds.</s>

**Comment by andyearnshaw** [comment]
@abitrolly I'm not looking for a lengthy debate that will end the same way as all the others before it, but I'll just point out there are plenty of people using TypeScript, despite the strictness and verbosity it adds to JavaScript.

Also, a ship that set off 30 years ago will take another 30 to come back for retrofitting. 😉

**Comment by abitrolly** [comment]
@andyearnshaw ~~a man who is not allowed to flip burgers in McDonalds, because he is a leper from sanctioned Belarus says that~~ making a FAQ with a short link that contains technical explanations that are based on evidence, will save you hours of debates and a dozen of insults. If you decide to be empathic to other people one day, you may also want to consider that such FAQ will also save them some precious time on rereading this thread.

**Comment by abitrolly** [comment]
I am unsubscribing. Thanks for all the fish.

**Comment by andyearnshaw** [comment]
@abitrolly it looks like you're conflating my comments with those of someone else in this thread. I have not used any insults and am fully empathetic towards the people requesting this feature. I do, however, understand why it is not possible to change how HTML is parsed at this point in time. I merely entered the discussion to offer an (potentially helpful) alternative to someone asking for self-closing tags.

**Comment by abitrolly** [comment]
@andyearnshaw I realize my mistake about attributing the insults to the wrong individual. That however, doesn't change my view that boasting about how big is your understanding does  not add any value to the understanding of others. I don't find the explanation "because it is too late" or "because it will break things" sufficient. Let's just admit there are no people who can make those experiments and provide proof links. We are all busy with our lives, and no matter how awesome our big tech corporation is, it will never allow its minions to waste its resources to the research of "What needs to die for people to write short tags for custom elements?". Guess that's a final nail to my coffin of finding a job. Have to "enjoy" my freedom.

**Comment by turboborsuk** [comment]
> Also, a ship that set off 30 years ago will take another 30 to come back for retrofitting. 😉

@andyearnshaw C'mon, that ship's been adrift with the crew paddling sideways most of the time. 😉

**Comment by sashafirsov** [comment]
@Danny-Engelman 
> There will never be self-closing custom elements.

You already wrong. The mix of HTML and XML is in place and in XML island like SVG or MathML closing tags are valid case. 
Have to experiment on XHTML island cross-browser with hope to dump dumb HTML in favor of strict XML. 

Perhaps the future would leave HTML behind, along with JS. The AST binary tree proposal seems doing slow but progress. In this tree it does not matter how parser would close the "tag", whether implicitly as in this proposal or XML, or by 1000+ weird rules as in HTML.

**Comment by alshdavid** [comment]
What's wrong with a self closing custom element? Seems useful in reducing verbosity in cases like custom input fields or icon wrappers where a closing tag is not necessary or misleading as to the behaviour of the element.

For instance:

```html
<custom-date-input format="iso" />
<fa-icon name="github" />
```
vs
```html
<custom-date-input format="iso"></custom-date-input>
<fa-icon name="github"></fa-icon>
```
Where the closing tag is unnecessary and implies to consumers that the element could contain children.

**Comment by ngdangtu-vn** [comment]
I don't understand why xml can self-closing tags freely and html cannot? What's the problem?

**Comment by tmoore411** [comment]
> I don't understand why xml can self-closing tags freely and html cannot? What's the problem?

 xml is invalid html, it goes through extra processing to be interpreted. HTML can't do that because it isn't an abstraction on top of itself, that's also what makes it different from TypeScript. Typescript isn't valid JavaScript and requires an additional build/transpilation step to be made into valid JavaScript. If you want self closing tags for web components in HTML, you'd have to change HTML and the sentiment seems to be that they aren't willing to make that kind of change to HTML (the backbone of the web). Frontend frameworks like React and Svelte can do it but that's because of JSX and again, an additional build step.

**Comment by ngdangtu-vn** [comment]
Well you are right and the relationship of XML/HTML is sibling rather than parent. So my question would be incorrect in term of technique, but in term of semantic it should be fine.

**Comment by crystalthoughts** [comment]
I would like to see this happen if possible. It signals information (leaf level node), and is more readable in that scenario.

**Comment by oelmekki** [comment]
From a user point of view, self closing custom elements is a no brainer, it would make our lifes better.

Deciding not to go with that because it would require big changes sounds like prioritizing machines (algorithm coherence, architecture tidiness, etc) over users (and their actual needs).

**Comment by firsspirit7** [comment]
Unsubscribe

**Comment by andyearnshaw** [comment]
@oelmekki 
> From a user point of view, self closing custom elements is a no brainer, it would make our lifes better.

We are not ordinary users, we are developers. From an actual web user point of view, self-closing custom elements would not benefit them in the slightest. Deciding not to go with self-closing custom elements actually benefits the user, for all the reasons already mentioned in this thread.

**Comment by abitrolly** [comment]
@andreasplesch 

> Deciding not to go with self-closing custom elements actually benefits the user, for all the reasons already mentioned in this thread.

Would you be so kind as to list all those benefits you aware of, to release fellow developer users from the burden of rereading almost 10 y/o thread?

EDIT: Plz.

**Comment by oelmekki** [comment]
>  Deciding not to go with self-closing custom elements actually benefits the user, for all the reasons already mentioned in this thread.

I have of course read the whole thread before commenting, and I don't see where you're getting that from. Beside the argument that "yeah, but doing that would require changes" (since when did we decide the web should never change? why exactly are browsers pushing updates every week, then?), the only maybe valid argument was that it would introduce XSS vulnerabilities, but when the author of that claim was asked to explain it, they never commented again (unless I missed something). What I *did* see, though, is an overwhelming majority of people expressing support for self-closing custom elements.

**Comment by alshdavid** [comment]
@abitrolly 

Arbitrary void elements `<foo>` are bad for parsers but self closing tags `<foo/>` are fine, ergonomic to consume and self documenting.

For example; if I create a custom element that abstracts an icon library, the following tag describes an element that does not have children elements, is concise to use and actually improves parser performance (because it doesn't need to search for a closing tag). 

```html
<x-icon type="chevron-right" />
```

However today the spec forces us to use a closing tag:
```html
<x-icon type="chevron-right"></x-icon>
```

This also applies to other use cases like custom inputs, radio buttons, checkboxes, etc. It's not a deal breaker obviously, but it is certainly more ergonomic than the requirement of a closing tag. 

Void elements are a no-go because it complicates parsers and could potentially mask erroneous code.

While the use case of custom elements is nice, should this apply to build-in elements too? `<div />` `<span />` and what does that imply for their semantics?

But the ultimate downside of self closing elements are that they are not backwards compatible so is it worth the migration effort? 🤷 

Personally I want to see support added (for custom elements at least) but the risk of breaking websites during the transition means it's not likely to be adopted

**Comment by besworks** [comment]
> `<x-icon type="chevron-right" />`

This is the **exact** use-case that has kept me subscribed to this issue for years. I hope we get it someday.

**Comment by oelmekki** [comment]
> But the ultimate downside of self closing elements are that they are not backwards compatible so is it worth the migration effort? 🤷

Can you elaborate on why it would not be backward compatible? I haven't seen that mentioned yet, and that would indeed be a serious issue in a standard. Is it just a case of "older parser will not know what to do with it", as adding any new feature would be (and then, I guess we can count of the fact that parsers always expect broken HTML), or is there something more fundamental that would break also pages not using self-closing custom elements?

> This is the exact use-case that has kept me subscribed to this issue for years. I hope we get it someday.

I'm quite convinced it will happen at some point, just because of the amount of people asking for it, no matter how vocal the minority of opposants are (just like types annotation in ECMA, which people keep asking for over and over). My guess would be that the reason there isn't much more activity here yet is because most developers don't yet use custom elements, or not directly. I can see it becoming only more noisy as they become more mainstream. Let's just hope we won't be retired by then. :)

**Comment by abitrolly** [comment]
Folks, I opened the issue https://github.com/WICG/webcomponents/issues/1104 that is solely for discussing self-closing elements. No void arguments or discussions on this dead issue anymore. I think we all agree here that void is no go.
