### ISSUE TITLE
Shadow dom innerhtml and CSP unsafe-inline

### ISSUE THREAD

**Issue by cardner** [WICG/webcomponents#627]
So libraries like reactjs have tried to address this issue with their latest release using CSX. Is there a plan for their either being a way to specify in a content security policy that inline style tags in the shadow dom are safe and don't violate the unsafe-inline policy? 
Or is there another alternative for having a strict CSP and still using shadow dom with inline style tags?

**Comment by rniwa** [comment]
Why are shadow DOM special? Why can't you just use a link element instead? (Safari 10 didn't support this but 10.1 would).

**Comment by cardner** [comment]
@rniwa I'm not sure I follow your suggestion entirely, could you elaborate a bit?

Also it's not necessarily just shadow DOM but more so when using shadow DOM along with the other APIs that are part of web components.
For example imagine if you wanted to use web components to build a robust library of UI elements that are client side and there for can be used and consumed by various technologies like python, javascript, or PHP. So you create custom elements with templates and imports to bring them to the glass. 
But while doing this you have to use them in an environment that applies a strict CSP that doesn't allow any inline style tags because it's really allow them all or none. So even if we used a style link in the custom element it would create an inline style tag that gets brought into the body element of the page which would violate the CSP even if located in the shadow DOM.

So my question is in a scenario like this is there a way to communicate to the CSP that the style tags in the shadow DOM are actually safe (if that may be the case)? 
I've done experiments where I would hash and checksum the style tags which would have to be run as part of the tool chain before pushing code to the server.

Would putting something similar to Subresource Integrity be a possible solution if the style tags were presumably rather static/non-changing?

**Comment by rniwa** [comment]
No, there is no mechanism like that.

The problem is that the security risk of using an inline styling doesn't change regardless of whether it's inside a shadow tree or not. Also, there is no way for browser to check whether a given shadow tree is created by a third party content (e.g. scripts from another source or a library) or the first party content.

The correct fix for those component authors to be using link element inside shadow trees instead of forcing users of the components to relax their CSP requirements.

**Comment by cardner** [comment]
I wouldn't never recommend relaxing the CSP requirements for the components, it would more likely just result in the use of web components being avoided as a whole for upcoming projects, which would be unfortunate in my opinion.

Wouldn't using a link element as an alternative lead to performance hinderances by creating additional requests? Especially if custom elements are being nested inside of each other? I realize that additional technologies like http2 would resolve a lot of this. But sometimes simply updating to http2 isn't so simple for some applications.

**Comment by rniwa** [comment]
Well, the fact using a link element instead of an inline style would result in an extra network load is an orthogonal issue to whether the said link element appears in a shadow tree or not.

We would have to solve the exact same issue with ES6 modules where a module could load more modules so I don't think it's an issue specific to web components.

**Comment by hayatoito** [comment]
We do not have a plan.
Shadow DOM should not be a security mechanism, so it is unlikely to treat a shadow tree as a unit of a kind of a security policy.

**Comment by annevk** [comment]
@cardner can't you use nonces? For third-party components this would require some secure out-of-band communication I guess, but they should work in theory.

**Comment by annevk** [comment]
Closing due to lack of response. If someone else hits this, this seems more like a general problem with `innerHTML` than with shadow trees.

**Comment by clshortfuse** [comment]
So, using Web Animation API can seem to be a solid workaround. Instead of templating like this:

````html
<div id="bar" style="{computeBarStyle()}">
````

You can instead:

````js
shadowRoot.getElementById('bar').animate([
  computeBarStyle()
 ], {
    duration: 0,
    fill: 'forwards',
  }
 );
 ````
 
It apparently works pretty well. I couldn't measure a performance difference. Not sure if it's an unintended "hack", to side step inline-styles, but if you're in shadow DOM, you're not letting your users manipulate shadow DOM trees anyway.

Only caveat is CSS Variables support for Web Animation API is non-existent on FireFox and Safari doesn't apply them to root. I've gone ahead and filed those issues, so if those get fixed, I would consider it production safe. It would just be on the Web Component author to apply styles in one sweep, instead of incrementally via `style.setProperty()`.
