### ISSUE TITLE
Agenda for W3C TPAC 2017 (Web Components)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#641]
Let me use this issue to collect any agenda candidates for [W3C TPAC 2017](https://www.w3.org/2017/11/TPAC/Overview.html) about Web Components.

**Comment by hayatoito** [comment]
Please allow me to note the following items, (by @rniwa), here:

> We would be interested in discussing the following items (not in any particular order) but we can do so over emails / Github issues as well:
- Declarative syntax
- Template instantiation & instance manipulation from JS
- HTML import replacement
- Isolated components

**Comment by hayatoito** [comment]
I can say Google would be interested in HTML import replacement, as HTML Modules.
ping @TakayoshiKochi, who might be the best person for HTML Modules.

Other than that, the following items might interest us:
- Constructable Styleheet Objects: http://tabatkins.github.io/specs/construct-stylesheets/
- CSS Shadow Parts: https://tabatkins.github.io/specs/css-shadow-parts/

**Comment by treshugart** [comment]
> Declarative syntax

If this in reference to "declarative shadow roots", it's something that the community has been screaming for, especially lately, and is the root of many criticisms from other communities.

As a community member, I'm interested in hearing more about the other points. Most notably "isolated components". If I may ask, what are these?

It's really nice to see some action started on these :)

**Comment by rniwa** [comment]
Apple would be interested in the topic of shadow parts as well.

**Comment by JanMiksovsky** [comment]
Three perennial issues that were deferred from v1:
* Extending input elements. This was originally couched in terms of extending arbitrary built-in elements, but all of the cases I've personally run up against have been the desire to extend `a`, `button`, and `input`. Perhaps focusing on a small set of extensible elements would lead to a better outcome?
* Submitting custom elements with a `form`.
* Some form of namespacing or scoping for custom elements to avoid markup collisions between hard-coded element names.

**Comment by rniwa** [comment]
Apple would be interested in discussing the form submission participation as well.

**Comment by domenic** [comment]
We already have a plan for form submission, but someone has to actually do the work... I took an action item, but never got around to it, unfortunately :(.

**Comment by rniwa** [comment]
Where was this proposed and what's the proposed solution?

**Comment by domenic** [comment]
https://github.com/w3c/webcomponents/issues/187 and https://github.com/w3c/webcomponents/issues/187#issuecomment-248003464

**Comment by hayatoito** [comment]
Regarding declarative shadow roots, here is the issue https://github.com/w3c/webcomponents/issues/71, which was closed due to a lack of a concrete proposal.

**Comment by rniwa** [comment]
> https://github.com/w3c/webcomponents/issues/187 and https://github.com/w3c/webcomponents/issues/187#issuecomment-248003464

Oh, you're talking about our proposal.

> Regarding declarative shadow roots, here is the issue https://github.com/w3c/webcomponents/issues/71, which was closed due to the lack of a concrete proposal.

Right. For each one of these, it would be ideal if people can come up with proposals beforehand instead of brainstorming at TPAC.

**Comment by justinfagnani** [comment]
@rniwa I'm very interested in working out a proposal for template parts, if you are too maybe we can make some time in the next few months.

**Comment by travisleithead** [comment]
Definitely would love to progress the discussion about isolated components, and a declarative shadow-dom.

**Comment by LJWatson** [comment]
Do you have any sense how much meeting time you'd like? Based on a day being divided into four blocks - could you give me an estimate? Thanks.

**Comment by rniwa** [comment]
Here's my estimate:
* Template & declarative syntax: ~2 hours
* Isolated components: ~1 hour
* HTML import replacement: 30min
* Form submission and other topics: 30min

**Comment by justinfagnani** [comment]
I suspect that HTML imports/modules will take more than 30 min, and is as important as templates, since they are where templates would live. Maybe we can take the combined 2.5 hours between them and divide it more evenly?

**Comment by LJWatson** [comment]
We have some flexibility in the WebPlat schedule at the moment, so increasing time on HTML imports/modules shouldn't be a problem.

Are there any other groups (or groups within WebPlat) you'd like to meet with, to discuss anything on your agenda?

**Comment by annevk** [comment]
I won't be there, but I recommend going through #661 at least. There's quite a few outstanding issues with "v1" and we don't have clear answers for each of them.

Someone should probably create a similar issue for custom elements. There's a couple issues there as well.

**Comment by snuggs** [comment]
Salutations @annevk. Be careful what you ask for. Just may get it _(especially when my career as an evangelist is starting to depend on the status of this)_ #664. Just dotting all the "I"s and crossing all the "T"(PAC)s 😎 

If accepted as a good curation may want to add #664 along with #661 to the topics of discourse. Otherwise, kill it with fire. I'm a New Yorker. tough skin, won't be upset. 💪 🍎 

I'm not sure of discussion regarding future features however since the last TPAC meeting there seems to be valuable interest in the following. These feel more `v2` ish and prefer leaving them here for fear of the bikeshed. Added my own personal experience and thoughts as well based on the past couple years dealing with custom elements deliberation that is beginning to produce casualties that are rolling downhill. Please take as an ephemeral grain of salt _(unless interested)_:

- [ ] Namespacing _(elements and attributes)_
- [ ] Self closing / void tags. _(e.g. `<x-foo> <!-- </x-foo> -->`)_ _([discussion](https://github.com/w3c/webcomponents/issues/113) & https://github.com/w3c/webcomponents/issues/624#issuecomment-292067997)_

Seems to be much related to namespacing in the platform spec unless i'm misinterpreting the moniker. _(See https://github.com/w3c/webcomponents/issues/634,
 [Section 4.3](https://w3c.github.io/webcomponents/spec/custom/#html:-creating-and-inserting-nodes) and [Section 4.4](https://w3c.github.io/webcomponents/spec/custom/#html:-parsing-xhtml-documents))_ `<acme-plastic-button>` vs. `<acme:plastic-button>`

It was actually _"fun"_ perusing the specs. Bug trackers & mailing list threads not so much.

**Comment by rniwa** [comment]
Apple's proposal for template instantiation has been posted to https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Template-Instantiation.md

We're working on a separate proposal on the declarative syntax for custom elements.

**Comment by smaug----** [comment]
FWIW, I can attend TPAC only remotely this time (wrong country for me).

Surprising to see proposals linked here, but not in the mailing list. I wouldn't have known about it if bkelly hadn't mentioned it to me.
(Initially that proposal looks like something which should be left to script libraries, but I could be totally wrong.)

**Comment by smaug----** [comment]
There are still some major spec issues, like https://github.com/w3c/webcomponents/issues/184
That was discussed last year. Did webkit try out the proposed fix for that? I think I haven't heard of that issue since then.

**Comment by yoichio** [comment]
I want to talk about [Selection API](https://www.w3.org/TR/selection-api/) for [Shadow DOM](https://www.w3.org/TR/shadow-dom/)(#79).

**Comment by yoichio** [comment]
Posted my proposal.
https://github.com/yoichio/public-documents/blob/master/selectionapiforshadow.md

**Comment by rniwa** [comment]
2017 TPAC is done.

**Comment by TakayoshiKochi** [comment]
Minutes: https://www.w3.org/2017/11/10-webplat-minutes.html

**Comment by annevk** [comment]
No discussion of existing issues if I'm reading those minutes correctly?

**Comment by TakayoshiKochi** [comment]
No, we went out of time after the big topics on agenda on that day.
