### ISSUE TITLE
Link to example from early in spec

### ISSUE THREAD

**Issue by brucelawson** [WICG/webcomponents#656]
In Shadow DOM spec https://w3c.github.io/webcomponents/spec/shadow/, please consider linking to the example in section 8 from various relevant places in the spec, eg in the definition of "slotable" (in the note in 2.2 which currently links to itself). I spent an hour trying to understand how to associate a light DOM node with its shadow DOM slot before I chanced upon the example at the bottom! Or - better still -  at the top of 2.2, explain and give an example. kthxbai

In light DOM, an element with a slot attribute of "<ident>" is inserted into Shadow DOM in a slot element with name="<ident>"

**Comment by hayatoito** [comment]
Sorry for wasting your time.
- Chapter 2, 3 and 4 of https://w3c.github.io/webcomponents/spec/shadow/ are just *copy* of https://dom.spec.whatwg.org/. Thus, what we have to do is to update https://dom.spec.whatwg.org/ directly.
- We haven't upstream-ed the example section from https://w3c.github.io/webcomponents/spec/shadow/ to https://dom.spec.whatwg.org/, which is unlikely to happen soon. The contribution is welcome.

I would rather remove Example section from  https://w3c.github.io/webcomponents/spec/shadow/, because it might be out-dated. :(
