### ISSUE TITLE
Upstreaming Shadow DOM and outstanding v1 work

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#661]
Previously: #377, #495.

- [x] 2. Shadow Tree (=> DOM Standard; information in "Shadow DOM" is obsolete)
- [x] 3. Mutation algorithms (=> DOM Standard; information in "Shadow DOM" is obsolete)
- [ ] 4. Events (=> DOM Standard, UI Events, Touch Events; information about UI and Touch already removed from "Shadow DOM" and the remainder is obsolete)
  - [x] DOM Standard
  - [x] UI Events: https://github.com/w3c/uievents/issues/157
  - [ ] Touch Events: https://github.com/w3c/touch-events/issues/84
- [ ] 5. User interaction
- [x] 6. HTML Elements in Shadow Trees (=> HTML Standard; information in "Shadow DOM" is obsolete)
- [ ] 7. Elements and DOM interfaces (=> DOM Standard and  HTML Standard)
  - [x] `DocumentOrShadowRoot` extensions
  - [x] Shadow.prototype.innerHTML: https://github.com/w3c/DOM-Parsing/issues/21

Outstanding issues in DOM and HTML:

- [ ] https://github.com/whatwg/dom/labels/shadow
- [ ] https://github.com/whatwg/html/labels/topic%3A%20shadow

Outstanding issues in this repository:

- [ ] https://github.com/w3c/webcomponents/issues?q=is%3Aopen%20label%3Av1%20label%3Ashadow-dom

**Comment by annevk** [comment]
The main thing lacking in OP is information about corresponding CSS efforts. There's https://drafts.csswg.org/css-scoping/ and https://github.com/w3c/csswg-drafts/labels/css-scoping-1 at least, but maybe there's more?

**Comment by snuggs** [comment]
@annevk perhaps update description. Missing a # 1.

> The main thing lacking in OP is information about corresponding CSS efforts. There's https://drafts.csswg.org/css-scoping/ and https://github.com/w3c/csswg-drafts/labels/css-scoping-1 at least, but maybe there's more?

What is the status with the pseudo class `:defined`? Seemed to be lacking in certain vendors but also could be merely a reflection of their respective overall status of Custom Elements which of course is outside the scope of this issue.

**Comment by annevk** [comment]
The numbers correspond to the sections in https://w3c.github.io/webcomponents/spec/shadow/.

**Comment by annevk** [comment]
`:defined` is now #665, though note it's not related to shadow trees.

**Comment by snuggs** [comment]
Ah yes i see now after re-assessing the steps section @annevk 🙏  Thanks for the clarification.

**Comment by Haprog** [comment]
The [Shadow DOM](https://www.w3.org/TR/shadow-dom/) spec used to declare that `DocumentOrShadowRoot` is extended with `elementFromPoint` and `elementsFromPoint`. Here's the latest web archive snapshot that still says so: https://web.archive.org/web/20180228173001/http://www.w3.org/TR/shadow-dom/

It seems that was since changed to a short page that basically just says:
> Shadow DOM specification is being incorporated into to the DOM specification, HTML specification, CSS Scoping Module Level 1, UI Events specification, and other relevant specifications.

I guess that was related to this issue? But I'm also very confused by where did that definition go.

The only current spec mentioning `elementFromPoint` and `elementsFromPoint` that I could find now is the [CSSOM View Module](https://drafts.csswg.org/cssom-view/) draft that specifies them on the `Document` only.

Related: https://github.com/w3c/csswg-drafts/issues/5886
See also: https://caniuse.com/mdn-api_documentorshadowroot_elementfrompoint

**Comment by Haprog** [comment]
So it kind of looks like `elementFromPoint` and `elementsFromPoint` were being dropped from the spec for `DocumentOrShadowRoot` since they were defined in Shadow DOM spec for that but there's no live spec reference for it anymore but I'm pretty sure this is not intentional.

This confusion also seems to have caused TypeScript to drop those methods from their DOM type definitions in TS 4.4 but looks like were added back in TS 4.5.

TypeScript 4.4 libdom changes (https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029)
> `DocumentOrShadowRoot`
> Removed: `caretPositionFromPoint`, `caretRangeFromPoint`, `elementFromPoint`, `elementsFromPoint`, `getSelection`

TypeScript 4.5 libdom changes (https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1143)
> `DocumentOrShadowRoot`
> Added: `elementFromPoint`, `elementsFromPoint`

**Comment by annevk** [comment]
They need to be defined in CSSOM. That hasn't happened yet, but as you found there's an issue tracking it.

**Comment by iameduardod** [comment]
Hi @annevk , any ETA when Shadow DOM / Roots will be included in web standards by W3C?

**Comment by annevk** [comment]
Already happened: https://dom.spec.whatwg.org/review-drafts/2020-06/.
