### ISSUE TITLE
light dom availability

### ISSUE THREAD

**Issue by jstrimpel** [WICG/webcomponents#673]
I do not think this is the correct place for this question, but if someone could point me in the right direction that would be great. Thanks.

Is there a deterministic approach for querying the light dom of a custom element? In the following example `this.children` is empty in the `console.log`, but the `console.log` wrapped in the `setTimeout` has 2 children.

```javascript
customElements.define('my-element', class MyElement extends HTMLElement {
  constructor() {
    super();        
    const shadowRoot = this.attachShadow({ mode: 'open' });           
  }
  
  connectedCallback() {
    console.log(this.children)
    setTimeout(() => { console.log(this.children); });      
  }
});
```

```html
<my-element>
  <div>First Child</div>
  <div>Second Child</div>
</my-element>
```

**Comment by jstrimpel** [comment]
Moved question to more appropriate project.

**Comment by rniwa** [comment]
You can't rely on your children to be present due to the way HTML parser works (it can add more children as the streamed content arrives). Instead, you should be doing work in child node's `connectedCallback`. If that's not possible, I'd suggest using `MutationObserver` to observe the changes to the child nodes. In general, there is no callback for when all children are inserted since there could be more children being inserted by DOM manipulation. See https://github.com/w3c/webcomponents/issues/619

**Comment by jstrimpel** [comment]
@rniwa That makes sense. Thanks for the replying and linking to the ticket that provides a bit of history and context.

**Comment by robdodson** [comment]
Also related if you're using a slot to distribute the content.
https://github.com/whatwg/dom/issues/447
