### ISSUE TITLE
Using attributes as properties

### ISSUE THREAD

**Issue by vrugtehagel** [WICG/webcomponents#913]
A lot of the web components I write use a pattern to connect an attribute to a property. Just like `id` is both an attribute and a property on any HTML element, I often want this pattern for custom attributes, leading me to write:
```
customElements.define('icon-button', class extends HTMLElement {
    static get observedAttributes(){ return ['icon']; }
    constructor(){
        super();
    }
    get icon(){ return this.getAttribute('icon'); }
    set icon(value){ this.setAttribute('icon', value); }
});
```
since this is a regularly recurring pattern, it would be really nice to get this out of the box as "attribute configuration". Of course, this configuring ideally shouldn't use any new properties on this class, so here's what I propose for the above:
```
customElements.define('icon-button', class extends HTMLElement {
    static get observedAttributes(){
        return [{name: 'icon', property: true}];
    }
    constructor(){
        super();
    }
});
```
This way, we can also extend it to get some more configuration options; for example, consider a boolean attribute. Currently, we need to write:
```
    static get observedAttributes(){ return ['important']; }
    get important(){ this.hasAttribute('important'); }
    set important(value){ this.toggleAttribute('important', value); }
```
but with configurable attributes, we can simply do something like
```
    static get observedAttributes(){
        return [{name: 'important', property: true, boolean: true}];
    }
```
We could even add things like getters and setters, that can transform the attribute's value (which is always a string or `null`) into something more directly usable. For example, this
```
    get serialNumber(){ Number(this.getAttribute('serial-number')); }
    set serialNumber(value){ this.setAttribute('serial-number', '' + value); }
```
could be written as
```
    static get observedAttributes(){
        return [{
            name: 'serial-number',
            property: true,
            get: value => Number(value),
            set: value => '' + value
        }];
    }
```
The configuration options, their names and its structure are up for debate, the main point is to allow for this type of configuration using objects as elements of the array returned by `observedAttributes`, where a string would just be a shorthand for the basic, unconfigured attribute.

**Comment by justinfagnani** [comment]
I'd rather keep the shape-defining aspects of a class declaration in the class body so that parsers, type-checkers, and the VMs can understand the class shape.

If decorators advance, I think some kind of built-in decorators would offer a nicer way of associating an attribute and property. I know people have posited a `@reflect` attribute before. I think an `@attribute` decorator would be easy to understand:

```ts
const attribute = Element.attributeDecorator;

class MyElement extends HTMLElement {
  @attribute({name: 'serial-number', type: Number})
  accessor serialNumber;
}
```

The question raised here would be how to populate `observedAttributes` from decorators. Decorators will be able to add metadata to a class, so a utility function could gather the attribute names. Maybe it's even possible that HTMLElement could have a default implementation of `static observedAttributes` that return this. I don't know how viable that it.

```ts
class MyElement extends HTMLElement {
  // 'foo' is an additional observed attribute not declared with a decorated field.
  static observedAttributes = ['foo', ...Element.getDeclaredAttributeNames(this)];
}
```

**Comment by rniwa** [comment]
It is problematic for `customElements.define` to start mutating the class being passed in. We've worked hard to avoid that when we were designing the API. Decorators do seem like a right solution for this.

**Comment by vrugtehagel** [comment]
I understand the class mutation is something unwanted - decorators seem like the perfect fit for this. Let's hope those get through!

**Comment by castastrophe** [comment]
What if the decorator itself declared it's inclusion in observedAttributes?  Something like:

```js
@attribute({ name: 'serial-number', type: Number, observed: true })
```

**Comment by trusktr** [comment]
> I'd rather keep the shape-defining aspects of a class declaration in the class body so that parsers, type-checkers, and the VMs can understand the class shape.



To clarify Justin's comment, decorators will be the only way to legitimately make this work in such a way that two things happen at once:

1. the class shape is defined using `class` fields, therefore before the `customElements.define` call the shape of the class is fully known using via `class` semantics,
2. and attributes can be mapped to JS properties or vice versa.

Otherwise, with an approach like `static observedAttributes = { foo: Element.attributes.number(123) }`, we may want the JS property to reflect back to the attribute, and in order for that to be possible the `customElements.define` call would need to modify the class (f.e. add a getter/setter pair on the prototype, plus extend the class so as to override class fields which use [[Define]] semantics) so that when a JS property is modified it would be able to react and serialize the value back into the attribute. If the engine does this, it is modifying the shape of the class dynamically without the user's use of class syntax, making it hard to analyze and understand. JS engines have optimizations in place for statically-analyzable class definitions (f.e. look how [V8 engine uses static information to optimize super calls now](https://v8.dev/blog/v8-release-90#faster-super-property-access)).

With decorators, we get both at once: we define JS properties as part of the class declaration so as to gain the benefits of a static definition, and with decorators we establish the desired to-attribute and/or from-attribute behavior that we want.
