### ISSUE TITLE
`customElements.upgrade` does not upgrade node subtrees cloned from `template` contents via `cloneNode`

### ISSUE THREAD

**Issue by Etherian** [WICG/webcomponents#946]
`customElements.upgrade` does not seem to upgrade node subtrees cloned from a `template` element via `cloneNode` in Firefox 95 and Chrome 96. I haven't tested other browsers.

Is this expected behavior?

(Code snippet from Danny Engelman's [answer](https://stackoverflow.com/a/70426998/5005318) to my Stack Overflow question about this behavior)
````javascript
class myEl extends HTMLElement {}

let el1 = document.createElement("my-el");
let el2 = Object.assign(document.createElement("template"), {
            innerHTML: "<my-el></my-el>"
          }).content.cloneNode(true).querySelector("my-el");

customElements.define("my-el", myEl);

customElements.upgrade(el1); // works as documented
customElements.upgrade(el2); // doesn't upgrade!

console.assert(el1 instanceof myEl, "element not upgraded");
console.assert(el2 instanceof myEl, "template not upgraded");
````

**Comment by rniwa** [comment]
> `customElements.upgrade` does not seem to upgrade node subtrees cloned from a `template` element via `cloneNode` in Firefox 95 and Chrome 96. I haven't tested other browsers.
> 
> Is this expected behavior?

Yes, this is expected because `el2`'s document is [**appropriate template contents owner document**](https://html.spec.whatwg.org/multipage/scripting.html#appropriate-template-contents-owner-document) of the document (which is `el1`'s document and where the custom element is defined). In order for upgrade to work, you must call `document.adoptNode` first. Alternatively, you can use `importNode` instead of `cloneNode` and clone the template contents using the correct document.

**Comment by rniwa** [comment]
I guess we could consider making `upgrade` automatically invoke `adoptNode` although that's a bit magical.

@domenic @annevk @justinfagnani WDYT?

**Comment by Etherian** [comment]
I think this snag could be handled via documentation without needing to modify the spec. I know a quick addendum on MDN's pages for `template` elements or `CustomElementRegistry.upgrade()` about how to use them with each other would have been enough for me. Is making suggestions about how to document features within the scope of this group?

**Comment by rniwa** [comment]
> I think this snag could be handled via documentation without needing to modify the spec. I know a quick addendum on MDN's pages for `template` elements or `CustomElementRegistry.upgrade()` about how to use them with each other would have been enough for me.

I see.

> Is making suggestions about how to document features within the scope of this group?

A clarification for author in the spec is within the spec of this issue tracker, updating MDN & other documentation is not.

**Comment by Jamesernator** [comment]
This will definitely be a confusing point if/when HTML modules happen, because in general one would be expecting to clone elements from documents other than the main document (e.g. `import { someTemplate } from "./someTemplate.html"`), and in general it would encourage more heavy use of HTML templates for web components so would be hit by developers much more frequently.

**Comment by trusktr** [comment]
One can also look at it this way: templates are supposed to be inert, and fast. That is why frameworks in benchmarks use `cloneNode` as the most speedy way to create element instances.

I don't know what the adoption process is, but elements gotten from cloneNode and inserted into the main document **_will_** be upgraded at that point.

**Comment by Jamesernator** [comment]
> One can also look at it this way: templates are supposed to be inert, and fast. That is why frameworks in benchmarks use `cloneNode` as the most speedy way to create element instances.
> 
> I don't know what the adoption process is, but elements gotten from cloneNode and inserted into the main document **_will_** be upgraded at that point.

The confusing point isn't that elements don't get upgraded on `cloneNode`, the confusing point is that calling `customElements.upgrade` **explicitly** on such elements doesn't do anything because they aren't associated to the main document.

I doubt most authors even know that there is a second document that templates associate their nodes to. The spec says the [motiviation for this is](https://html.spec.whatwg.org/multipage/scripting.html#appropriate-template-contents-owner-document):

> Each [Document](https://html.spec.whatwg.org/multipage/dom.html#document) not created by this algorithm thus gets a single [Document](https://html.spec.whatwg.org/multipage/dom.html#document) to act as its proxy for owning the [template contents](https://html.spec.whatwg.org/multipage/scripting.html#template-contents) of all its [template](https://html.spec.whatwg.org/multipage/scripting.html#the-template-element) elements, so that they aren't in a [browsing context](https://html.spec.whatwg.org/multipage/browsers.html#browsing-context) and thus remain inert (e.g. scripts do not run). Meanwhile, [template](https://html.spec.whatwg.org/multipage/scripting.html#the-template-element) elements inside [Document](https://html.spec.whatwg.org/multipage/dom.html#document) objects that are created by this algorithm just reuse the same [Document](https://html.spec.whatwg.org/multipage/dom.html#document) owner for their contents.

I don't see why such a concept need exist. Like scripts not connected to a document (e.g. created by `.createElement`) don't evaluate even though their `.ownerDocument` is `document`. The trigger for script evaluation is connectedness, which template nodes never are anyway as they're part of a document fragment which isn't connected to the main document.

Even setting the template weirdness aside, the fact is the whole point of `customElements.upgrade` is that it can upgrade elements *without* connecting them. The fact that it can't upgrade elements from a template document is pretty arbitrary given that it's entirely possible to adopt into the main document, upgrade, then return the elements to the previous document.

**Comment by rniwa** [comment]
F2F resolution: This is working as intended.

**Comment by trusktr** [comment]
3 years later and I stumbled on this again. It is very confusing. As @Jamesernator mentioned:

> The confusing point isn't that elements don't get upgraded on `cloneNode`, the confusing point is that calling `customElements.upgrade` **explicitly** on such elements doesn't do anything because they aren't associated to the main document.

Upgrades are, for sure, the most frustrating aspect of Custom Elements. This `upgrade()` fuels that fire.

In case it helps anyone who stumbles here, I'll show an example that doesn't work, and how to make it work.

Not working ([codepen](https://codepen.io/trusktr/pen/pvggjyo/07a5cda8275fd7692efaec6d0a5a92b5)):

```js
class MyEl extends HTMLElement {
  constructor() {super(); console.log('MyEl constructor')}
}
customElements.define('my-el', MyEl)

const template = document.createElement('template')
template.innerHTML = '<my-el></my-el>'

const frag = template.content.cloneNode(true)

console.log(customElements.get('my-el')) // MyEl

customElements.upgrade(frag) // crickets
console.log('My el constructor should have ran already')

document.body.append(frag) // logs "MyEl constructor"
```

Working ([codepen](https://codepen.io/trusktr/pen/myVVemG/bf6477874326074de429e5d73834386a)):

```js
class MyEl extends HTMLElement {
  constructor() {super(); console.log('MyEl constructor')}
}
customElements.define('my-el', MyEl)

const template = document.createElement('template')
template.innerHTML = '<my-el></my-el>'

 // logs "MyEl constructor"
const frag = document.importNode(template.content, true) // <--- MODIFIED

console.log(customElements.get('my-el')) // MyEl

// customElements.upgrade(frag) //                        <----- REMOVED
console.log('My el constructor should have ran already')

// document.body.append(frag) // not needed for upgrade
```
