### ISSUE TITLE
Add getElementsByPartName() that returns live collection.

### ISSUE THREAD

**Issue by bahrus** [WICG/webcomponents#964]
First, an embarrassing question:  What is the equivalent of element.querySelectorAll('.class-name') for parts?

Even if that exists, I for one would find the ability to quickly get a live collection quite useful.  Anyone else?

**Comment by matthewp** [comment]
`element.querySelectorAll('[part~=name]')` should work no?

**Comment by bahrus** [comment]
Often it would work, but it's not 100% precise, I don't believe.

Update:  Can't think of any counterexamples, so you are probably right.

**Comment by rniwa** [comment]
We don't want to add a new live NodeList / HTMLCollection since they slow down DOM operations of the entire document due to various implementation constraints.

**Comment by bahrus** [comment]
Thanks for considering and the explanation.

**Comment by sashafirsov** [comment]
@rniwa,
>We don't want to add a new live NodeList / HTMLCollection since they slow down DOM operations of the entire document due to various implementation constraints.

Live NodeList is a generic pattern people found quite useful and is a part of standard. I do not understand the reason of restraining developers of such useful pattern. It is an app developer decision whether the performance impact critical or not.  

The Part is just one of the nodes in the DOM. What is the reason to make it an exception from generic DOM API?
I do not see the given "not performant" as an excuse. If generic DOM API good enough, let it cover the whole DOM including Parts. 

With all due respect. this ticket has to be reopened at least to collect opinions from potential consumers. The question on subject did not appear from the sky. It is a valid pattern and many app developers would be willing to sacrifice some performance in order to make data-responsive page. Most of such uses would be applied on already generated static page where performance would be spent exclusively on serving the binding, ideally via live NodeList. Such use case has NO impact on DOM performance.

**Comment by sashafirsov** [comment]
> We don't want to add a new live NodeList
@rniwa , Could you, please be more specific on who are "we" so it could be addressed accordingly?

**Comment by Danny-Engelman** [comment]
There is no 

* ``this.shadowRoot.getElementsByTagName`` 

* and ``this.shadowRoot.getElementsByClassName``

either

Tested in Chromium/FireFox: https://jsfiddle.net/WebComponents/9yrtn8vb/

**Comment by CamdynR** [comment]
@Danny-Engelman the ShadowRoot [inherits from DocumentFragment](https://dom.spec.whatwg.org/#interface-shadowroot) not from Element or Document, so ShadowRoot does not have methods like [getElementsByClassName](https://dom.spec.whatwg.org/#ref-for-dom-document-getelementsbyclassname%E2%91%A0) and [getElementsByTagName](https://dom.spec.whatwg.org/#ref-for-dom-document-getelementsbytagname%E2%91%A0). Document and DocumentFragment both inherit from Node, but do not share all methods.
